beamer-bridge/beamer

- frontend/src/App.vue
- frontend/src/components/RequestDialog.vue
- frontend/src/components/RequestFormInputs.vue
- frontend/src/components/inputs/Selector.vue
- frontend/src/main.css
- frontend/src/views/Home.vue
This PR should cover most of the comments about the UI and its responsiveness.
> UI adjustments

- brownie-config.yaml
This includes some fixes. See https://github.com/ethereum/solidity/releases/tag/v0.8.13
> contracts: Update solidity

- contracts/contracts/RequestManager.sol
when a claim is challenged for the first time it must be challengePeriod + challengePeriodExtension
> contracts: challengePeriod after the first challenge 

- Makefile
- beamer/agent.py
- beamer/chain.py
- beamer/events.py
- beamer/request.py
- beamer/tests/test_request.py
- docs/source/agent.rst
- docs/source/claim_state_machine.dot
- docs/source/request_state_machine.dot
First draft of separating requests and claims
* improve claim states
>  agent: separate request and claims logic

- beamer/tests/conftest.py
- contracts/contracts/RequestManager.sol
- contracts/scripts/deploy.py
- contracts/scripts/deploy_optimism.py
- contracts/tests/conftest.py
- contracts/tests/test_request_manager.py
- contracts/tests/utils.py
- scripts/deployment/main.py
- scripts/deployment/rinkeby_testnets.json
introduce a mapping from for finalization times per chain id.
If not contained target chain id is not supported by the protocol.
> contracts: mapping for finalization time per target chain id

- frontend/src/App.vue
- frontend/src/components/ImprintModal.vue
> frontend: Add imprint dialog box to frontend

- frontend/src/components/ImprintModal.vue
App scrollbar has been affected by custom scrollbar for imprint modal  
dialog. Modal dialog scrollbar styled has been limited to it.
> frontend: Fix app scrollbar style

- beamer/events.py
Resolves #509 
I'm not super happy with the implementation, if you have any idea how to do this in a nicer way let me know.
> agent: Handle log range limiting on boba

- beamer/chain.py
- beamer/request.py
- beamer/state_machine.py
- beamer/tests/agent/test_handlers.py
Based on #515
- Make some functions free, so that they can be used in tests.
- Use those functions to test the removal of old requests and claims
Resolves https://github.com/beamer-bridge/beamer/issues/356
> Testability

- frontend/src/components/RequestFormInputs.vue
- frontend/src/composables/useRequestTransaction.ts
- frontend/src/composables/useTokenBalance.ts
- frontend/src/services/transactions/token.ts
Close #262 
This adds a small text below the amount field, which shows the balance of the currently selected token. The functionality for fetching the token balance is implemented in a new composable. The balance is fetched once and updated by subscribing to ERC20's `Transfer` event.
> frontend: Display token balance below amount field

- contracts/contracts/RequestManager.sol
- scripts/deployment/main.py
Resolves #496 
We don't need an explicit check, because we have a check here now: https://github.com/beamer-bridge/beamer/blob/082a23ad9a956f61e0861e132f6b26603a8f42ba/contracts/contracts/RequestManager.sol#L158
I also appended a little commit that re-orders the requires, so that we burn less gas if a require should be hit.
> Disallow self as target chain

- beamer/agent.py
- beamer/chain.py
- beamer/events.py
- beamer/state_machine.py
- beamer/tests/agent/test_cli.py
- beamer/tests/conftest.py
> agent: Query events from ResolveRegistry

- beamer/chain.py
- beamer/models/claim.py
- beamer/tests/contracts/test_request_manager.py
- contracts/contracts/RequestManager.sol
- docs/source/agent.rst
See https://github.com/beamer-bridge/beamer/issues/568
Todo: update docs maybe, but PR for whitepaper is pending
> Minmum bid

- beamer/agent.py
- beamer/cli.py
- beamer/config.py
- beamer/state_machine.py
- beamer/tests/agent/test_handlers.py
- beamer/tests/conftest.py
This will be required to call the message relayer with the correct data.
Related to #271
> agent: Add config to Context

- docs/source/protocol.rst
- docs/source/whitepaper.rst
Add section about griefing attack on stake in whitepaper.
closes https://github.com/beamer-bridge/beamer/issues/568
> Reword docs about minimum outbid of claimer

- beamer/tests/agent/test_challenge.py
- beamer/tests/agent/test_request.py
- beamer/tests/contracts/test_request_manager.py
- beamer/tests/contracts/test_request_manager_fees.py
- beamer/tests/util.py
- contracts/contracts/RequestManager.sol
- docs/source/glossary.rst
- docs/source/whitepaper.rst
> Percentage fee model

- .github/workflows/backend.yml
- contracts/contracts/BeamerUtils.sol
- contracts/contracts/CrossDomainRestrictedCalls.sol
- contracts/contracts/FillManager.sol
- contracts/contracts/OptimismProofSubmitter.sol
- contracts/contracts/RequestManager.sol
- contracts/contracts/ResolutionRegistry.sol
- contracts/contracts/Resolver.sol
- contracts/contracts/RestrictedCalls.sol
- contracts/contracts/StandardToken.sol
- contracts/interfaces/IProofSubmitter.sol
> Contract formatting

- scripts/call_contracts.py
Found out during Arbitrum testing.
> scripts: fix call_contracts.py after the recent fee changes

- docs/source/contributing.rst
- scripts/generate_account.py
This is useful to have and will be used in the upcoming e2e scripts, so to get this out of the way...
> Add an account generation script

- beamer/tests/agent/test_challenge.py
- beamer/tests/agent/test_request.py
- beamer/tests/contracts/test_fill_manager.py
- beamer/tests/contracts/test_request_manager.py
Needed a little filler issue without the need to think.
Resolves #646
> tests: Use `alloc_accounts` everywhere

- .gitmodules
- docker/arbitrum/arbitrum.sh
- scripts/deployment/arbitrum-local.json
This merely sets up the environment infrastructure -- tests are to come with follow-up PRs.
Closes #626.
> Add an E2E test environment for Arbitrum

- beamer/tests/contracts/test_request_manager.py
- beamer/tests/contracts/test_resolution_registry.py
- contracts/contracts/RequestManager.sol
- contracts/contracts/ResolutionRegistry.sol
Check upon withdraw if the fillhash is invalidated
> Withdraw invalid hash

- beamer/chain.py
- beamer/tests/agent/unit/test_challenge.py
- beamer/tests/agent/unit/test_handlers.py
- beamer/tests/agent/unit/test_invalidate.py
- beamer/tests/agent/unit/utils.py
fixes: #571 
tests are missing yet
> Agent: engage in ongoing challenges only at unfilled requests

- beamer/tests/contracts/test_request_manager.py
- contracts/contracts/RequestManager.sol
> contracts: Add deprecation switch to RequestManager

- beamer/chain.py
- beamer/state_machine.py
- beamer/tests/agent/unit/test_handlers.py
- beamer/tests/agent/unit/test_invalidate.py
Resolves #674 
Resolves https://github.com/beamer-bridge/beamer/issues/547
> Withdraw invalidated claims

- beamer/tests/contracts/test_request_manager.py
- contracts/contracts/RequestManager.sol
> Add transfer limit in contracts

- beamer/chain.py
> Agent needs to sleep when there are unprocessed events in the queue

- beamer/models/claim.py
- docs/source/claim_state_machine.dot
> agent: Allow claim state transition from started to withdrawn

- beamer/state_machine.py
only count fill requests once they are processed
only count valid requests from the agent's perspective
> metrics: Improve metrics reporting

- beamer/agent.py
- beamer/chain.py
- beamer/tests/agent/test_cli.py
> agent: adapt poll frequency on RPC endpoints depending on l1 chain id

- scripts/deployment/main.py
> scripts: Margin gas price strategy for l1

- contracts/contracts/CrossDomainRestrictedCalls.sol
- contracts/contracts/FillManager.sol
- contracts/contracts/RequestManager.sol
- contracts/contracts/ResolutionRegistry.sol
- contracts/contracts/Resolver.sol
- contracts/contracts/RestrictedCalls.sol
- contracts/interfaces/IMessenger.sol
- contracts/interfaces/IProofSubmitter.sol
- docs/source/conf.py
- docs/source/contracts-api-reference.rst
- docs/source/contracts.rst
- docs/source/index.rst
- poetry.lock
- pyproject.toml
> Contract docs

- frontend/src/composables/useTokenBalance.ts
fixes #598
It turns out that the filter for the events is also being executed for "past" events. According to this here: https://github.com/ethers-io/ethers.js/issues/1504 events are emited for the current block.
So what happens is - I execute a transfer, reload the page and my balance is wrong because I received the current block. But my balance was already updated.
My workaround for now is to only fetch the balance from the contract and not to try to calculate it myself.
> Fix wrong balance displayed when sending a tx

- scripts/deployment/arbitrum-local.json
- scripts/deployment/ganache-local.json
- scripts/deployment/main.py
- scripts/deployment/optimism-local-template.json
- scripts/deployment/rinkeby_testnets.json
> Deployment script arguments

- beamer/events.py
- beamer/state_machine.py
- beamer/tests/agent/unit/test_l1.py
- contracts/contracts/RequestManager.sol
> Add FinalizationTimeUpdated event

- beamer/events.py
- beamer/state_machine.py
- beamer/tests/agent/test_challenge.py
- beamer/tests/agent/unit/test_l1.py
- beamer/tests/conftest.py
- beamer/tests/contracts/test_request_manager.py
- beamer/tests/contracts/test_request_manager_fees.py
- contracts/contracts/RequestManager.sol
- docs/source/protocol.rst
- docs/source/whitepaper.rst
- scripts/deployment/arbitrum-local.json
- scripts/deployment/ganache-local.json
- scripts/deployment/main.py
- scripts/deployment/optimism-local-template.json
- scripts/deployment/rinkeby_testnets.json
> Contract naming

- .dockerignore
- .github/workflows/agent-release.yml
- .github/workflows/container-image.yml
- .github/workflows/prepare-package.yml
Try to fix the current CI problems
> ci: Fix relayer packaging

- frontend/src/views/Home.vue
> frontend: fix connect wallet button

- frontend/src/components/RequestSourceInputs.vue
- frontend/src/composables/useFaucet.ts
> frontend: Do not show the faucet button at all in production

- frontend/public/config.production.json
- frontend/src/actions/transfers/transfer.ts
- frontend/src/components/RequestSourceInputs.vue
- frontend/src/components/RequestTargetInputs.vue
- frontend/src/composables/useChainSelection.ts
- frontend/src/services/web3-provider/ethereum-provider.ts
- frontend/src/services/web3-provider/metamask-provider.ts
- frontend/src/services/web3-provider/types.ts
- frontend/src/services/web3-provider/walletconnect-provider.ts
- frontend/tests/unit/actions/transfers/transfer.spec.ts
- frontend/tests/utils/mocks/ethereum-provider.ts
Closes #852 
See commit messages for details.
Not related to this PR but I also fixed the config file for production which wasn't parsable  since my last PR.
> frontend: Fix chain switching logic and keep source chain selector in sync

- .dockerignore
- Makefile
- docker/Dockerfile.agent
This should improve docker image build times as well as save something on the final image size.
We're still at ~1.3GB, which is not ideal and we should probably reconsider going back to shiv or something.
> Docker changes

- beamer/agent.py
This is one of the things Jannik ran into, part of #919.
> beamer: agent: improve error reported when we don't find contract info

- frontend/src/services/transactions/request-manager.ts
Fixes #741
In order to avoid RPC endpoint spam there was a need of an adaptive
transfer expiry event listening.
Previously, the transfer expiry check was attached and called each
time a new block was produced. That is, from the moment a transfer
was created and until it expires we would have this listeners active
for each transfer stored in the `localStorage` that is still pending.
With this change we will use adaptive listeners attached once
the transfer enters the time-frame where it is actually expected
to expire.
All the possible scenarios are covered with this impl.
1. If transfer didn't enter expected expiration time-frame when
checking against sequencer clock && our clock
- We sleep until the transfer enters the expected expiration
time-frame by our clock
2. If transfer entered …
> frontend: Delay request expiry listener

- deployments/mainnet/deployment.json
> deployments: mainnet: update with new Boba deployment

- docker/arbitrum/arbitrum.sh
- docker/scripts/common.sh
- docs/source/contributing.rst
- scripts/generate_account.py
> chore: Add password option to generate_account.py

- frontend/public/config.production.json
Updating RequestManager contract addresses to reflect the latest mainnet setup.
> frontend: Update request-manager mainnet addresses

- frontend/src/composables/useRequestSourceInputValidations.ts
> frontend: Validate amount when token not selected

- frontend/src/components/layout/Progress.vue
> frontend: Fix error message overflow & progress line gaps

- beamer/models/request.py
- beamer/state_machine.py
- docs/source/request_state_machine.dot
> Allow l1 resolve transition in other states

- frontend/src/components/TransferHistory.vue
- frontend/src/components/layout/LazyWrapper.vue
- frontend/tests/unit/components/layout/LazyWrapper.spec.ts
Fixes #965  
Fixes #998 
Fixes #988 
Check commit message for more info on  #965 solution.
> frontend: Fix several issues related to transfer history container

- docs/source/faq.rst
- docs/source/index.rst
> docs: add FAQ

- scripts/call_contracts.py
> request returns a tuple (withdrawInfo) instead of depositReceiver

- docs/source/faq.rst
> docs: fix format issues in faqs

- beamer/tests/constants.py
- contracts/contracts/RequestManager.sol
> Remove unused variables in Request

- frontend/src/App.vue
- frontend/src/components/Feedback.vue
> frontend: integrate chatbot

- docs/source/contracts-api-reference.rst
- docs/source/contracts.dot
- docs/source/contracts.rst
- docs/source/l1_resolution.rst
- docs/source/running.rst
- docs/source/whitepaper.rst
Main changes:
- Request manager / Resolution registry merge
- removal of fill hash
- new RestrictedCalls interface
resolves: #1033
As a reviewer, please download the branch, read the full docs, and comment on anything which is not understandable.
> Update docs after contract simplifications

- frontend/src/components/RequestFeeTooltip.vue
- frontend/src/components/RequestSourceInputs.vue
- frontend/src/composables/useMinRequestFee.ts
- frontend/src/services/transactions/request-manager.ts
- frontend/tests/unit/components/RequestFeeTooltip.spec.ts
- frontend/tests/unit/composables/useMinRequestFee.spec.ts
Solves the frontend part of issue #1049.
Once again, i saw the opportunity to refactor the `RequestSourceInputs` and split some of the tooltip related code to its own component (since its not a plain html anymore).
Provided tests for the newly created components as well as composables.
> frontend: implement dynamic min. fee notification & refactor `RequestSourceInputs.vue`

- docs/source/whitepaper.rst
> docs: adjust the agent fee

- frontend/src/components/WalletConnectionDetails.vue
- frontend/src/components/wallet/ConnectionError.vue
- frontend/src/components/wallet/Disconnect.vue
- frontend/src/composables/useWallet.ts
- frontend/src/views/Home.vue
- frontend/tests/unit/components/WalletConnectionDetails.spec.ts
- frontend/tests/unit/components/wallet/ConnectionError.spec.ts
- frontend/tests/unit/components/wallet/Disconnect.spec.ts
- frontend/tests/unit/composables/useWallet.spec.ts
Resolves #1041 
While working on it, i seized the opportunity to slightly refactor the `Home.vue` code. I scattered the code inside it related to the wallet connection status into their own separate components. This chores will be very appreciated later on when we need to prepare a full test setup.
Also provided tests for all the new components & new features.
The folder/file naming could be done better IMO. Happily open for discussions/suggestions!
> frontend: Add wallet disconnect feature & refactor home view

- frontend/src/services/transactions/token.ts
closes #1094 
Just changing the approval amount to the value of a transfer. Pretty straight forward.
> Frontend: Only ask for approval of transfer value

- frontend/src/App.vue
closes #1048
Adds two links to https://beamerbridge.com. First from logo, second from footer.
> frontend: Add links to BeamerBridge website

- frontend/src/App.vue
- frontend/src/services/transactions/token.ts
This pr merges the fix commits for #1048 & #1094 to the mainnet instance branch
> Update frontend mainnet

- frontend/src/composables/useWallet.ts
- frontend/src/services/web3-provider/ethereum-provider.ts
- frontend/src/services/web3-provider/types.ts
- frontend/tests/unit/composables/useWallet.spec.ts
- frontend/tests/utils/mocks/ethereum-provider.ts
Fixes #692 
Read commit description.
> frontend: recognize internal wallet disconnect

- frontend/src/services/web3-provider/ethereum-provider.ts
Since we are positioned as an ETH rollup to rollup bridge for the beginning i implemented it using static code. 
Could be improved by defining `nativeCurrency` for each chain in the config file but that requires a decent amount of work and also not needed atm.
Fixes #1109
> frontend: fix new network native currency display

- beamer/middleware.py
- beamer/util.py
Fixes the problem described in https://github.com/beamer-bridge/beamer/issues/1086#issuecomment-1270735862.
Part of #1086.
> Fix simple cache

- beamer/tests/contracts/test_request_manager.py
- contracts/contracts/RequestManager.sol
- docs/source/whitepaper.rst
> Disallow challenges after L1 resolution/invalidation

- beamer/tests/contracts/test_fill_manager.py
- contracts/contracts/FillManager.sol
- docs/source/whitepaper.rst
> Prohibit invalidation of previous block hash

- beamer/agent.py
- beamer/middleware.py
- beamer/util.py
Part of #1086.
This simply cherry-picks the few relevant commits to `0.x` branch.
> Backport middleware caches

- frontend/index.html
> frontend: include matomo tracking script

- .circleci/config.yml
- .github/workflows/backend.yml
- poetry.lock
- pyproject.toml
And also update all dependencies.
> pyproject.toml: raise minimum Python version to 3.10

- contracts/contracts/FillManager.sol
- contracts/contracts/RequestManager.sol
- contracts/contracts/Resolver.sol
- contracts/contracts/chains/arbitrum/ArbitrumMessengers.sol
With the prereport of the audit some optimizations were suggested.
closes #1114
> Optimizations on contracts

- frontend/index.html
Added:
- tracking visitors across all subdomains
- prepend the site domain to the page title when tracking
- outlines report hide clicks known alias URLS of beamer
> Cherry pick new frontend features

- frontend/src/components/RequestSourceInputs.vue
- frontend/src/composables/useMaxTransferableTokenAmount.ts
- frontend/src/services/transactions/request-manager.ts
- frontend/src/services/transactions/utils.ts
- frontend/src/types/uint-256.ts
- frontend/tests/unit/composables/useMaxTransferableTokenAmount.spec.ts
- frontend/tests/unit/services/transactions/request-manager.spec.ts
- frontend/tests/unit/services/transactions/utils.spec.ts
- frontend/tests/unit/types/uint-256.spec.ts
Brings the "Use Max" token amount button feature on the app's mainnet instance.
> Integrate "Use Max" button feature on mainnet

- frontend/src/components/Feedback.vue
closes https://github.com/beamer-bridge/team/issues/7
> frontend: fix chatbot popup on scroll

- frontend/package.json
- frontend/src/components/layout/Expandable.vue
- frontend/src/main.ts
- frontend/yarn.lock
> Frontend: Minor optimizations

- frontend/src/components/RequestSourceInputs.vue
- frontend/src/composables/useRequestSourceInputValidations.ts
- frontend/src/composables/useTransferLimit.ts
- frontend/src/services/transactions/request-manager.ts
- frontend/tests/unit/composables/useTransferLimit.spec.ts
> frontend: add token transfer limit validation

- frontend/config/chains/10.json
- frontend/config/chains/1337.json
- frontend/config/chains/28.json
- frontend/config/chains/288.json
- frontend/config/chains/588.json
- frontend/config/chains/chain.ts
- frontend/config/schema.ts
- frontend/package.json
- frontend/src/components/RequestSourceInputs.vue
- frontend/src/components/RequestTargetInputs.vue
- frontend/src/components/Transfer.vue
- frontend/src/components/inputs/BasicInput.vue
- frontend/src/components/inputs/Input.vue
- frontend/src/components/inputs/NumericInput.vue
- frontend/src/components/inputs/Selector.vue
- frontend/src/composables/useChainSelection.ts
- frontend/src/directives/vFocusOnMount.ts
- frontend/src/services/web3-provider/ethereum-provider.ts
- frontend/src/services/web3-provider/types.ts
- frontend/src/types/data.ts
- frontend/tests/unit/components/Transfer.spec.ts
- frontend/tests/unit/components/inputs/BasicInput.spec.ts
- frontend/tests/unit/components/inputs/NumericInput.spec.ts
- frontend/tests/unit/components/inputs/Selector.spec.ts
- frontend/tests/unit/directives/vFocusOnMount.spec.ts
- frontend/tests/utils/data_generators.ts
- frontend/tests/utils/mocks/directives.ts
- frontend/yarn.lock
This PR contains the cherry-picked commits (fixes) for the following issues:
- #1165 
- #1124
> Update mainnet frontend

- docs/source/branching-strategy.rst
- docs/source/contributing.rst
- docs/source/index.rst
This documents the agreed points from today's discussion.
@fredo @GabrielBuragev @manuelwedler @compojoom please take a look and provide feedback.
> Add branching strategy

- docker/arbitrum/arbitrum.sh
- docs/source/whitepaper.rst
> Fix: typos

- .gitignore
- Makefile
- docs/source/contributing.rst
- relayer/package.json
- relayer/yarn.lock
- scripts/call_contracts.py
Fixes some issues mentioned in #1230.
The idea is not to resolve #1230 entirely, but at least to make the onboarding the new dev less painful.
Closes: #1234.
> Misc fixes

- beamer/events.py
- beamer/tests/contracts/test_request_manager.py
- beamer/tests/contracts/test_request_manager_fees.py
- contracts/contracts/RequestManager.sol
implments: #613 
Edit: Note that in line 651 msg.Sender was changed to claimReceiver (not claimResolver)
> Withdraw on behalf of others

- beamer/events.py
- contracts/contracts/RequestManager.sol
> Add sender to RequestCreated event

- contracts/contracts/RequestManager.sol
use uint96 for stakes so that we can access claim states with less read operations
> Stakes to be uint96

- frontend/index.html
fixes: https://github.com/beamer-bridge/beamer/issues/1226
> frontend: modify matomo code

- .circleci/workflows.yml
Thanks to Daniel for the idea.
> .circleci: allow simpler cache key change via an env variable

- frontend/src/App.vue
- frontend/tailwind.config.js
See https://github.com/beamer-bridge/marketing/issues/234
Just adds a banner to notify users that Beamer is live on Arbitrum.
> frontend: Add Arbitrum notification banner

- .circleci/workflows.yml
This also moves the docs build out of the backend into a proper workflow.
> .circleci: simplify docs-related workflow/jobs

- frontend/package.json
This will effectively reset the localStorage of all the users that will visit beamer.
> frontend: bump major version

- scripts/call_contracts.py
call_contracts.py still expected request id to be integer
> scripts: make request id option to bytes

- frontend/.eslintrc.js
- frontend/src/App.vue
- frontend/src/components/Version.vue
- frontend/src/env.d.ts
- frontend/src/stores/transfer-history/store.ts
- frontend/tests/unit/components/Version.spec.ts
- frontend/vite.config.ts
> frontend: add commit hash inside footer

- beamer/agent.py
- beamer/chain.py
- beamer/events.py
- beamer/state_machine.py
- beamer/tests/agent/unit/test_handlers.py
- beamer/tests/agent/unit/test_invalidate.py
EventMonitor is adapted to use related chain_ids and using both contracts to fetch events.
> EventMonitor fetch all events per chain

- frontend/src/components/RequestSourceInputs.vue
- frontend/src/composables/useRequestSourceInputValidations.ts
closes #1206 #1439 
New behavior when users wallet balance is higher than the transfer limit:
https://user-images.githubusercontent.com/18466333/218754464-5d88d999-f67e-4f88-bbbb-c4c1a7135f13.mov
---
~~@olympe-silve i rephrased the button & tooltip and added some color adjustments to the tooltip text so things are more visible.~~
> Frontend: improve use max button

- contracts/contracts/chains/arbitrum/ArbitrumMessengers.sol
- contracts/contracts/chains/ethereum/EthereumMessengers.sol
Closes #1494, #1395 
Didn't do any manual tests as we lack automated deployment support for Ethereum as another rollup.
This will be tackled in https://github.com/beamer-bridge/beamer/issues/1398
> Ethereum messenger contracts

- beamer/agent/events.py
- beamer/tests/agent/test_rpc_errors.py
> agent: Fix failing to sync agent on quicknode

- .circleci/workflows.yml
- docs/source/releasing.rst
This PR
- changes the CI trigger for container image workflow so that we build a container image on each tag
- updates docs to provide more details on releasing
> Misc updates

- relayer/.gitignore
- relayer/jest.config.ts
- relayer/package.json
- relayer/src/assets/abi/EthereumL2Messenger.json
- relayer/src/assets/abi/FillManager.json
- relayer/src/common/events/RequestFilled.ts
- relayer/src/map.ts
- relayer/src/services/arbitrum.ts
- relayer/src/services/ethereum.ts
- relayer/src/services/index.ts
- relayer/src/services/types.ts
- relayer/tests/unit/common/events/RequestFilled.spec.ts
- relayer/tests/unit/map.spec.ts
- relayer/tests/utils/data_generators.ts
- relayer/tsconfig.json
- relayer/yarn.lock
> Ethereum relayer service

- contracts/contracts/chains/arbitrum/ArbitrumMessengers.sol
- relayer/src/services/arbitrum.ts
> Add automatic withdrawal inside ArbitrumL1Messenger

- beamer/health/check.py
- beamer/health/health-check-mainnet.conf
- beamer/health/util.py
- beamer/tests/health/conftest.py
closes #1525 
Note: Any future token will be easily supported by simply adding it to the list of tokens in the config file
> Add multi-token support to monitoring script

- docs/source/commands.rst
- docs/source/configuration.rst
- docs/source/index.rst
- docs/source/running.rst
> Docs: Add health-check command

- beamer/agent/agent.py
- beamer/agent/chain.py
- beamer/agent/commands.py
- beamer/agent/config.py
- beamer/agent/data/agent.conf.example
- beamer/agent/events.py
- beamer/health/check.py
- beamer/tests/agent/multiple_processors/test_multiple_event_processors.py
- beamer/tests/agent/test_cli.py
- beamer/tests/agent/test_request.py
- beamer/tests/agent/unit/utils.py
- beamer/tests/conftest.py
- docs/source/commands.rst
- docs/source/configuration.rst
> Handle reorgs for agent

- beamer/agent/events.py
So that we can have target_weight_ppm instead of target_weight_p_p_m.
> beamer: agent: improve camel to snake case conversion

- scripts/deployment/arbitrum-local-template.json
- scripts/deployment/config.py
- scripts/deployment/ethereum-local.json
- scripts/deployment/ganache-local.json
- scripts/deployment/goerli-testnets.json
- scripts/deployment/mainnet.json
- scripts/deployment/optimism-local-template.json
Property case has been changed to snake case.
courtesy of chatGPT
> scripts: Change property name casing in deployment

- relayer/src/services/arbitrum.ts
- relayer/src/services/ethereum.ts
> Relayer: Await relayMessage transaction of EthereumMessenger

- beamer/agent/middleware.py
- beamer/agent/util.py
- beamer/tests/agent/multiple_processors/_test_slave.py
- beamer/tests/agent/multiple_processors/test_multiple_event_processors.py
> Support type 2 transactions

- relayer/src/assets/abi/Resolver.json
- relayer/src/services/ethereum.ts
> relayer: add missing check for already relayed messages

- frontend/src/App.vue
> frontend: change banner text

- docs/source/whitepaper.rst
current fee values will come in a sperarate PR
> docs: update the fee section for new minLpFee calculation

- docs/source/_static/css/styles.css
> docs: adapt mermaid to dark mode

- frontend/src/components/RequestSourceInputs.vue
> frontend: fix source token selection reactivity

- beamer/agent/chain.py
- beamer/agent/state_machine.py
- beamer/tests/agent/test_challenge.py
- beamer/tests/agent/unit/test_challenge.py
- beamer/tests/agent/unit/utils.py
- beamer/tests/util.py
- poetry.lock
- pyproject.toml
> feat: change challenge strategy

- docs/source/_static/css/styles.css
> docs: fix loopText css for dark mode

- deployments/artifacts/goerli/420-optimism.deployment.json
- deployments/artifacts/goerli/421613-arbitrum.deployment.json
- deployments/artifacts/goerli/5-ethereum.deployment.json
- deployments/artifacts/goerli/84531-base.deployment.json
- deployments/artifacts/goerli/base.deployment.json
- deployments/artifacts/mainnet/1-ethereum.deployment.json
- deployments/artifacts/mainnet/10-optimism.deployment.json
- deployments/artifacts/mainnet/42161-arbitrum.deployment.json
- deployments/artifacts/mainnet/base.deployment.json
> feat: convert deployment file

- docker/optimism/optimism.sh
- relayer/src/map.ts
- relayer/src/services/optimism.ts
> e2e: disable optimism relayer and prepare addresses for relayer

- Makefile
Introduce a `difflint` command which runs all python linters against modified/added files only.
___
The purpose of dummy `.difflint` file added to the repo is a need to provide at least a single file to all linters. Tried hard to have a condition in the Makefile to run linters only if any file is subjected for linting (check if `$(FILES)` variable is empty) but unsuccessful. Feel free to share a suggestion on a workaround. According to my research, this one should work but it doesn't:
```
difflint:
$(eval FILES := $(shell git status --porcelain | grep --color=never -E $(DIFFLINT_RE) | awk '{print $$NF}'))
ifneq ($(FILES),)
mypy $(FILES) .difflint
black --check --diff $(FILES) .difflint
flake8 $(FILES) .difflint
isort $(FILES) .difflint --diff --check-only
pylint $(FILES) .difflint
endif …
```
> Add difflint Makefile target

- contracts/contracts/chains/polygon_zkevm/PolygonZkBridgeInterface.sol
- contracts/contracts/chains/polygon_zkevm/PolygonZkEVMMessengers.sol
> contracts: implement polygon zkevm messengers

- .pylintrc
- beamer/agent/chain.py
- beamer/agent/models/claim.py
- beamer/agent/state_machine.py
- beamer/agent/util.py
- beamer/middleware.py
- beamer/tests/util.py
- beamer/util.py
- scripts/deployment/main.py
https://github.com/beamer-bridge/beamer/issues/1812
> Reflect pylint suggestions

- scripts/verify-contracts.py
> scripts: implement contract verifier script

- deployments-npm-package/package.json
Let's see what will go wrong now
> deployments: npm package v2.0.0

- beamer/agent/state_machine.py
- beamer/deploy/artifacts.py
- beamer/deploy/commands.py
- beamer/deploy/util.py
- beamer/events.py
This is a set of simpler changes I did while working on the config read command, submitting this separately so as to minimise the config read command PR material and potential conflicts.
> Add missing events, improve typing

- frontend/src/App.vue
- frontend/src/actions/transfers/allowance-information.ts
- frontend/src/actions/transfers/index.ts
- frontend/src/actions/transfers/request-information.ts
- frontend/src/actions/transfers/transaction-information.ts
- frontend/src/actions/transfers/transfer.ts
- frontend/src/components/RequestDialog.vue
- frontend/src/composables/useContinueInterruptedTransfers.ts
- frontend/src/composables/useTransferRequest.ts
- frontend/src/services/transactions/request-manager.ts
- frontend/src/services/transactions/token.ts
- frontend/src/services/web3-provider/ethereum-provider.ts
- frontend/src/services/web3-provider/safe-provider.ts
- frontend/src/services/web3-provider/types.ts
- frontend/tests/unit/actions/transfers/allowance-information.spec.ts
- frontend/tests/unit/actions/transfers/request-information.spec.ts
- frontend/tests/unit/actions/transfers/transaction-information.spec.ts
- frontend/tests/unit/actions/transfers/transfer.spec.ts
- frontend/tests/unit/composables/useContinueInterruptedTransfers.spec.ts
- frontend/tests/unit/composables/useTransferRequest.spec.ts
- frontend/tests/unit/services/web3-provider/ethereum-provider.spec.ts
- frontend/tests/utils/data_generators.ts
- frontend/tests/utils/mocks/ethereum-provider.ts
- frontend/tests/utils/mocks/ethers.ts
> frontend: Fix continuing of transfers

- .github/ISSUE_TEMPLATE/rollup-integration.md
Added the testnet and testing steps to the template.
> Add testnet todos to template

- scripts/verify-contracts.py
This PR fixes the missing contract verifications problem caused by artifact restructuring.
> fix: add base chain contracts to verification

- docs/source/contributing.rst
Fix two errors encountered while following https://docs.beamerbridge.com/contributing.html for sake of running agent on local.
> Update contributing page

- .circleci/workflows.yml
At least until we sort out the failures that occur with the node.
> .circleci: disable Polygon zkEVM tests

- beamer/agent/chain.py
- beamer/agent/models/claim.py
- beamer/agent/relayer.py
- beamer/tests/agent/unit/test_challenge.py
> feat: add OP message prove

- frontend/config/chains/10.json
- frontend/config/chains/chain.ts
- frontend/config/schema.ts
- frontend/src/components/OptionDisabledTooltip.vue
- frontend/src/components/RequestSourceInputs.vue
- frontend/src/components/inputs/Selector.vue
- frontend/src/composables/useChainSelection.ts
- frontend/src/types/data.ts
- frontend/src/types/form.ts
- frontend/tests/unit/components/OptionDisabledTooltip.spec.ts
- frontend/tests/unit/components/inputs/Selector.spec.ts
- frontend/tests/unit/composables/useChainSelection.spec.ts
- frontend/tests/utils/data_generators.ts
> Frontend: Add Selector option disabling feature & disable OP with tooltip

- docs/source/releasing.rst
> docs: add info on how to publish the npm package

- relayer/src/services/relayer/optimism.ts
Check commit messages for more info.
Closes #1925
> relayer: add fallback relay via OP CDMessenger

- relayer/src/ethers/json-rpc-provider.ts
- relayer/src/services/relayer/optimism.ts
- relayer/src/services/types.ts
- relayer/tests/unit/ethers/json-rpc-provider.spec.ts
> Relayer: Implement remaining OP Bedrock requirements

- .circleci/workflows.yml
- docker/arbitrum/arbitrum.sh
- docker/optimism/optimism.sh
- docker/polygon_zkevm/polygon_zkevm.sh
- docker/scripts/common.sh
Fixes the flaky e2e tests on arbitrum. In addition to that it makes it possible to run the tests locally on Mac M1
> Relayer arb e2e

- .circleci/workflows.yml
- beamer/contracts.py
- docker/optimism/optimism.sh
- scripts/_util.py
- scripts/call_contracts.py
- scripts/e2e-test-fill.py
- scripts/e2e-test-op-commands.py
> feat: op relayer fallback e2e

- beamer/config/commands.py
- beamer/config/state.py
- beamer/tests/agent/test_cli.py
- beamer/tests/config/test_read.py
- beamer/tests/config/test_write.py
- beamer/tests/config/util.py
- beamer/tests/util.py
- docs/source/commands.rst
This PR adds the `config write` command, related tests and docs.
Closes: #1832
> Config write

- beamer/agent/agent.py
- beamer/agent/chain.py
- beamer/agent/config.py
- beamer/agent/data/agent.conf.example
- beamer/agent/state_machine.py
- beamer/agent/util.py
- beamer/tests/agent/conftest.py
- beamer/tests/agent/multiple_processors/test_multiple_event_processors.py
- beamer/tests/agent/test_challenge.py
- beamer/tests/agent/test_cli.py
- beamer/tests/agent/test_pending_tx_handling.py
- beamer/tests/agent/test_rate_limiter.py
- beamer/tests/agent/test_read_timeout.py
- beamer/tests/agent/test_request.py
- beamer/tests/agent/test_rpc_errors.py
- beamer/tests/agent/unit/test_challenge.py
- beamer/tests/agent/unit/utils.py
- beamer/tests/conftest.py
- beamer/util.py
- docs/source/configuration.rst
> Introduce minimum source balance

- docker/polygon_zkevm/polygon_zkevm.sh
I was too fast to merge this PR https://github.com/beamer-bridge/beamer/pull/1976
Addressed @istankovic comments here.
> relayer: use variables for replace in sed

- beamer/config/commands.py
- beamer/config/state.py
- beamer/tests/config/test_read.py
- beamer/tests/config/test_write.py
This is to ensure checksum stability.
> beamer: config: replace set with a list

- frontend/src/actions/transfers/transfer.ts
- frontend/src/services/transactions/token.ts
- frontend/tests/unit/actions/transfers/transfer.spec.ts
- frontend/tests/unit/services/transactions/token.spec.ts
> frontend: Show error if allowance needed

- relayer/src/cli/programs/prove-op-message.ts
- relayer/src/services/relayer/optimism.ts
- relayer/tests/unit/cli/programs/prove-op-message.spec.ts
> relayer: OP relayer needs to print proof timestamp

- beamer/tests/conftest.py
- beamer/tests/contracts/test_fee_sub.py
- contracts/contracts/FeeSub.sol
> FeeSub contract

- beamer/agent/chain.py
- beamer/agent/relayer.py
- beamer/tests/agent/unit/test_challenge.py
> fix: use timestamp from relayer

- CHANGELOG.md
- poetry.lock
- pyproject.toml
> release: v2.4.0

- frontend/src/actions/transfers/subsidized-transfer.ts
- frontend/src/actions/transfers/types.ts
- frontend/src/components/ShareTweet.vue
- frontend/src/stores/transfer-history/serializer.ts
- frontend/tests/unit/components/ShareTweet.spec.ts
- frontend/tests/unit/stores/transfer-history/serializer.spec.ts
- frontend/tests/utils/data_generators.ts
See #1684
Should only be merged shortly before we go live on Polygon.
> frontend: Update transfer success tweet text for Polygon release

- beamer/agent/chain.py
- beamer/chains.py
- beamer/deploy/util.py
- beamer/tests/agent/multiple_processors/test_multiple_event_processors.py
- beamer/tests/agent/unit/test_challenge.py
- beamer/tests/agent/unit/utils.py
- beamer/util.py
> feat: support type2 for op

- frontend/config/chains/1.json
- frontend/config/chains/10.json
- frontend/config/chains/1101.json
- frontend/config/chains/42161.json
- frontend/src/App.vue
- frontend/src/components/ShareTweet.vue
- frontend/tests/unit/components/ShareTweet.spec.ts
Implements a part of: #2050 as well as enables 🦓 !
> frontend: enable fee subsidy

- frontend/config/chains/1101.json
- frontend/src/components/ShareTweet.vue
- frontend/tests/unit/components/ShareTweet.spec.ts
Do not merge until further notice!
> frontend: enable polygon zkevm

- beamer/health/health-check-mainnet.conf
the run-your-own-agent repo conf is updated, but the one inside the health check folder isn't.
> health: upadate health check with zkevm conf

- relayer/package.json
- relayer/src/services/relayer/map.ts
- relayer/tests/unit/map.spec.ts
- relayer/yarn.lock
> relayer: add support for Base

- frontend/src/actions/transfers/subsidized-transfer.ts
- frontend/src/actions/transfers/transfer.ts
- frontend/tests/unit/actions/transfers/subsidized-transfer.spec.ts
- frontend/tests/unit/actions/transfers/transfer.spec.ts
- frontend/tests/unit/components/ShareTweet.spec.ts
- frontend/tests/unit/stores/transfer-history/serializer.spec.ts
- frontend/tests/utils/data_generators.ts
There are still no tests for this file as it requires some effort.
> frontend: extend subsidized transfers with missing functionality

- frontend/config/chains/8453.json
> frontend: add base network

- frontend/src/components/layout/Banner.vue
Closes https://github.com/beamer-bridge/www.beamerbridge.com/issues/67
> change banner text

- beamer/agent/chain.py
Also provide provide claim in the log to facilitate debugging.
> beamer: agent: emit a log entry when OP prove is successful, too

- beamer/tests/contracts/test_request_manager.py
- contracts/contracts/RequestManager.sol
The PR fixes the correct resolution during resolution by invalidation
> use claim fill id during invalidation resolution

- beamer/config/commands.py
- beamer/config/state.py
- beamer/deploy/config.py
- beamer/tests/config/test_write.py
- beamer/tests/contracts/test_request_manager.py
- contracts/contracts/RequestManager.sol
> feat: allow removing chain

- beamer/tests/contracts/test_request_manager.py
- contracts/contracts/RequestManager.sol
> feat: remove require from withdraw

- beamer/deploy/config.py
- deployments/config/goerli/1442-polygon-zkevm.json
- deployments/config/goerli/420-optimism.json
- deployments/config/goerli/421613-arbitrum.json
- deployments/config/goerli/5-ethereum.json
- deployments/config/goerli/84531-base.json
- deployments/config/local/1001-polygon-zkevm.json
- deployments/config/local/1337-ethereum.json
- deployments/config/local/412346-arbitrum.json
- deployments/config/local/901-base.json
- deployments/config/local/901-optimism.json
- deployments/config/mainnet/1-ethereum.json
- deployments/config/mainnet/10-optimism.json
- deployments/config/mainnet/1101-polygon-zkevm.json
- deployments/config/mainnet/42161-arbitrum.json
- deployments/config/mainnet/424-public-goods-network.json
- deployments/config/mainnet/8453-base.json
fees, and chain parameters which are changable are removed from deployment config as they are not needed there. They are configure by beamer config write commands along with desired state files
> Remove config parameters from deployment config

- beamer/artifacts.py
- beamer/check/commands.py
- beamer/tests/check/test_invalidations.py
- beamer/tests/util.py
- docs/source/commands.rst
Part of #1646, this introduces a command to verify L1 invalidations.
Coverage:
> Beamer check verify invalidations

- docs/source/index.rst
- docs/source/relayer.rst
- docs/source/whitepaper.rst
- relayer/README.md
> Add relayer documentation

- beamer/tests/deploy/test_deploy.py
> beamer: tests: add tests for `deploy` and `deploy-base` commands
