- frontend/src/services/transactions/token.ts
For every request, user was asked to make first a transaction for
giving permission to access token balance. This was happening because
everytime the persmission was given over the amount going to be sent.
We changed that to give the permission over the whole token balance
instead. By that, the permission transaction will happend once, unless
the user has made a request for a sum more than the initial balance
Resolves:
https://github.com/beamer-bridge/beamer/issues/353
> frontend: Limit permission for token transactions

- beamer/contracts.py
- beamer/tests/test_cli.py
- scripts/deployment/main.py
This will make it easier to check depolyments later.
⚠️ As this changes the format of the deployment file, this will make the agent not work until a new depolyment.
> deploy: Store deployment args in deployment file

- beamer/chain.py
- beamer/events.py
- beamer/request.py
- contracts/contracts/RequestManager.sol
While we are about to change the contracts, I would like to squeeze this PR in and add the `validUntil` to the `RequestCreated` Event so that it presents complete information over the request.
As an optimization, we don't need to fetch request data after we have received the event with the necessary infromation anyway and safe us a RPC call. We all know how unforeseeable RPC calls can behave, and can delay processing the events by quite some bit.
> contracts: add valid until to event

- beamer/agent.py
- beamer/chain.py
- beamer/state_machine.py
- beamer/tests/test_handlers.py
- beamer/tests/test_request.py
@istankovic @fredo A first WIP for the state machine restructuring.
Let me know what you think.
> agent: Restructure state machine

- README.md
- docs/source/contributing.rst
- scripts/deployment/ganache-local.json
- scripts/deployment/main.py
This updates the instructions on how to run and test agents locally.
It also extends the deployment script to allow deployments to a local ganache instance.
Part of #411.
> Docs fixes

- frontend/src/App.vue
- frontend/src/components/RequestFormInputs.vue
- frontend/src/services/web3-provider/metamask-provider.ts
- frontend/src/services/web3-provider/types.ts
Because user doesn't have an information about the token going to be  
used in testing, so it will be hard to see how the system is working,  
a button to add the token to metamask is available for the user to  
easily watch the token in metamask.  
A small fix for the imprint link repalcing the dot separator with a  
bullet.
Resolves:  
#463
> frontend: Add button to add token to metamask

- frontend/src/components/RequestDialog.vue
- frontend/src/services/transactions/request-manager.ts
After changing configuration it appears that we were using the same  
token address of source rollup for both source and target token address,  
as they were equal anyway, so the issue didn't appear before they are  
different in new condiguration. As there's no way to map source and  
target token addresses, we used the token symbol temporarily for this  
mapping until we figure out another proepr way to make this.  
Also the unnecassry event check at the request end was causing issue,  
it has been removed anyway.
> Fix uncompleted request on frontend

- frontend/src/App.vue
It's no longer required for the current stage to collect feedback   
using the chatbot, so it has been disabled.
Resolves:  
beamer-bridge/marketing#41
> frontend: Disable typeform feedback

- beamer/request.py
Resolves https://github.com/beamer-bridge/beamer/issues/518
This is a strange case where the agent filled a request but didn't claim
in time.
This has been seen on testnet.
> agent: Allow request transition from filled to ignored 

- frontend/src/components/RequestDialog.vue
- frontend/src/components/RequestFormInputs.vue
If user was in progress screen and then changed network from metamask,  
when trying to make a new transfer, a change network error occurs. This  
happens because once network is changed, page should be reloaded, and  
we are applying this action only in form screen. We moved the watcher to  
the parent RequestDialog component and it should work on both screens  
now. The side effect of this is that, progress screen reloads to form  
screen on changing networks, but I think this's acceptable for the sake  
of avoiding the error. In future, once we have a proper state managemnet  
, we can use it to keep the UI state as well so we avoid this reload  
side effects.
> frontend: Fix network change error in progress screen

- frontend/src/services/transactions/fill-manager.ts
We turn on event listener on target chain after a successful transaction  
to listen to fulfillment event, event listener keeps working and send  
unnecessary requests to RPC. It is now removed after sucessful event  
listening or timout.
> frontend: Remove traget chain event listener after finishing

- frontend/src/components/RequestFormInputs.vue
Because of an issue on bridge when user is trying to send a request from  
source chain to the same one as traget chain, it was required to filter  
target chain selector and remove chosen source chain from the list.
Resolves:  
#495
> frontend: Remove source chain from target chain selector

- beamer/state_machine.py
- beamer/util.py
This allows us to get rid of a lot of `eth_getCode` requests, namely one request (~0.2s each) per incoming request.
Part of #477
> agent: Skip token contract code check when using match checker

- beamer/agent.py
- beamer/chain.py
- beamer/events.py
- beamer/state_machine.py
- beamer/tests/agent/test_handlers.py
Currently black data are queried from RPC in handlers when required.
This is ineffective, as most of these requests will get the same return
value.
Instead, we add a mapping from chain id to block data to the `Context`,
in which the latest known block for each chain is stored. It is updated
via the new `LatestBlockUpdated` event.
Part of https://github.com/beamer-bridge/beamer/issues/477
> agent: Cache latest block data

- beamer/events.py
This will save some RPC requests when no new blocks are available.
As commented from @istankovic
> agent: Query block data later when getting events

- .github/dependabot.yml
There are no tests yet, so we don't know if stuff breaks.
@weilbith As discussed.
> chore: Disable dependabot for frontend

- .github/workflows/base.yml
Using Git's feature of fixup commits is a good practice for pull requests. But all fixup commits must be always resolved first before merging the pull request finally. To ensure nobody can forget this, it is always very useful to have the continuous integration pipeline to verify this.
I'm completely open to rename the workflow from `base` to anything else. No strong opinion here. I thought about something like `shared` or so. 🤷🏾
> add new base workflow to block fixup commit merges

- beamer/chain.py
- beamer/tests/agent/test_handlers.py
This was forgotten when implementing GC and brings us from 3000 active
requests down to 20 requests on testnet.
> agent: GC ignored requests as well

- .github/workflows/container-image.yml
This will allow us to trace back an image to the relevant source tree, as well as pick "known-good" images in case the latest image ends up being broken.
> .github: tag container images with git commit IDs

- beamer/agent.py
- beamer/cli.py
- beamer/metrics.py
- beamer/state_machine.py
- beamer/tests/conftest.py
- poetry.lock
- pyproject.toml
This uses the `prometheus_client` Python package to set up an endpoint that serves some simple data about the running agent,
as outlined in #468.
Part of #468.
I've tested the endpoint locally and it seems to work alright. The next step would be to configure our Prometheus server to poll our agents' endpoints periodically. Once that is done, we can close #468.
> Set up a Prometheus metrics endpoint

- .github/workflows/backend.yml
This will avoid running agents tests when jst frontend is touched.
I decided to run in on merges to `main` unconditionally, so we have data there.
> ci: Make agent tests conditional in pure frontend PRs

- beamer/tests/contracts/test_l1_resolution.py
- contracts/contracts/ResolutionRegistry.sol
Resolves #563 
In the function I needed to add the `resolutionChainId` parameter, as this is necessary to check the call chain.
> contracts: Add `invalidateFillHash` to `ResolutionRegistry`

- docs/source/protocol.rst
- docs/source/whitepaper.rst
See issue #346 and #492 for discussion
Idk if we should keep the idea of parallel claims to solve the "self-challenge" problem in the case the request was honestly filled. We could think about replacing it with the honest filler joining the challenge game as a third party. I'm fine with w/e.
> Add non-fill proofs to whitepaper

- beamer/tests/contracts/test_l1_resolution.py
- contracts/contracts/Resolver.sol
fixes: #565 
I reused the `Resolution` event when sending a Non-Fill Proof with `filler = address(0)`. I thought this is sufficient as we have a more expressive event in `ResolutionRegistry.sol`.
> contracts: add resolveNonFill to L1 Resolver.sol

- frontend/src/components/RequestFormInputs.vue
- frontend/src/components/inputs/Selector.vue
- frontend/src/formkitTheme.ts
Close #526 
Fixes the text of all form fields to be aligned on the same side. I decided for the right side as it is in Olympe's design.
> frontend: Left align all form fields

- frontend/package.json
The deployment on DO fails because of an old NodeJS version.
This is solved by specifying a recent version in the package file. I tested this on DO and it works.
> chore: Specify node version in frontend

- beamer/chain.py
- beamer/tests/agent/test_challenge.py
- beamer/tests/agent/test_request.py
I believe that without this, the agent will attempt to withdraw any invalid claim that were contested by someone else:
1- Bob makes wrong claim
2- Charles challenges
3- Claim expires and Charles wins
4- Agent (that did not participate so far) tries to withdraw
Also, without the `continue` in the withdraw `if` clause, the agent will try to challenge a terminated claim.
The withdraw does not fail, and instead sends the funds to Charles because that's how it is in the contracts, but I don't believe the Agent should do that.
I attempted to write a test and could actually verify the behaviour with logs, but since the withdraw tx does not fail, it's hard to write an effective test.
Idk if we should transition the claim to `ignored` state, I don't fully understand this.
> Update withdraw claim strategy to only withdraw own winning claims

- beamer/chain.py
- beamer/tests/agent/test_challenge.py
- beamer/tests/agent/test_request.py
https://github.com/beamer-bridge/beamer/pull/593 had some lint errors which occured during the CI after merging to main. 
I dont know why it did not fail on the PR
> fix lint errors from previous merge

- beamer/events.py
- beamer/tests/contracts/test_fill_manager.py
- beamer/tests/contracts/test_l1_resolution.py
- beamer/tests/contracts/test_request_manager.py
- contracts/contracts/FillManager.sol
- contracts/contracts/OptimismProofSubmitter.sol
- contracts/contracts/ResolutionRegistry.sol
- contracts/contracts/Resolver.sol
- contracts/interfaces/IProofSubmitter.sol
Part of #271 
This lets us map the l1 resolution events to the request.
> Add request ID to L1 resolution data

- beamer/tests/agent/test_challenge.py
- beamer/tests/util.py
a quick fix to calculate the correct gas spending by using tx_receipt.gasUsed
> Use tx_receipt.gasUsed instead of tx.gas for gas spending calculation in tests

- README.md
- beamer/agent.py
- beamer/chain.py
- beamer/cli.py
- beamer/config.py
- beamer/events.py
- beamer/l1_resolution.py
- beamer/models/claim.py
- beamer/models/request.py
- beamer/state_machine.py
- beamer/tests/agent/test_cli.py
- beamer/tests/agent/test_handlers.py
- beamer/tests/agent/utils.py
- beamer/tests/conftest.py
- docs/source/contributing.rst
- docs/source/request_state_machine.dot
- docs/source/running.rst
Resolves #271 
The main work for initiating and handling L1 resolution. Some follow-ups will be needed one we have the new challenge and non-fill proofs integrated.
This is hopefully readable on a per-commit basis. Some important things that are added:
- Add the L1 RPC URL to the CLI and config
- Add the `InitiateL1ResolutionEvent`. It triggers a check if the L1 resolution is viable (financially) and triggers it in this case.
- Important caveat: This currently only takes one claim into account. Do we want to fix this?
- Resolution is triggered by adding a new task to the `resolution_pool`. This is a `ThreadPoolExecutor` with one worker, which takes care of serializing multiple parallel resolutions.
- The `RequestResolved` event is handled in the state machine and writes the correct filler …
> L1 resolution

- brownie-config.yaml
This should not be needed anymore with new ganache.
See 07bb2c6f1c5b42c7c1fe6b62b39280eb7a883d4e more details.
> brownie-config.yaml: remove the explicit chain ID setting

- frontend/src/actions/transfers/transfer.ts
- frontend/src/components/RequestDialog.vue
- frontend/src/components/TransferStatus.vue
- frontend/src/composables/useRequestFee.ts
- frontend/src/composables/useTransfer.ts
- frontend/src/services/transactions/request-manager.ts
- frontend/src/types/data.ts
- frontend/src/types/token-amount.ts
- frontend/tests/unit/actions/transfers/transfer.spec.ts
- frontend/tests/unit/components/TransferStatus.spec.ts
- frontend/tests/unit/types/token-amount.spec.ts
- frontend/tests/utils/data_generators.ts
This adds a sourceAmount and targetAmount (type: TokenAmount) to Transfer and removes the sourceToken, the targetToken and the amount.
The tokens can now be accessed from the amounts. This also enables later having a different target amount from the source one.
Also it makes the fees a TokenAmount because the fee model changes and we do not want to break backwards compatibility with encoding in the local storage.
For convenience an EthereumAmount class is created which inherits from the TokenAmount and sets the right symbol when created.  This type is also now used in the useRequestFee composable. Later, the composable will need to be adapted to the new fee model and use a TokenAmount.
> frontend: Improve types of the properties of Transfer

- beamer/events.py
- beamer/models/claim.py
- beamer/state_machine.py
- beamer/tests/agent/unit/test_handlers.py
- beamer/tests/agent/unit/test_invalidate.py
- beamer/tests/contracts/test_fill_manager.py
- beamer/tests/contracts/test_l1_resolution.py
- beamer/tests/contracts/test_request_manager.py
- beamer/tests/contracts/test_resolution_registry.py
- contracts/contracts/FillManager.sol
- contracts/contracts/OptimismProofSubmitter.sol
- contracts/contracts/ResolutionRegistry.sol
- contracts/contracts/Resolver.sol
- contracts/interfaces/IProofSubmitter.sol
The agent must find the corresponding request by the fill hash.
For simplicity I chose iterating over claims and reconstructing the fill hash to find the corresponding requests / claims.
This is only a temporary change and will be changed soon by #645 changes in the resolution registry. In that PR we can optionally introduce optimizations on the agent to find the corresponding objects more efficiently.
> Remove request ID in L1 contract events

- frontend/.eslintrc.js
- frontend/src/actions/transfers/transfer.ts
- frontend/src/components/RequestDialog.vue
- frontend/src/components/inputs/Selector.vue
- frontend/src/composables/useChainSelection.ts
- frontend/src/composables/useFaucet.ts
- frontend/src/composables/useLoadConfiguration.ts
- frontend/src/composables/useTokenSelection.ts
- frontend/src/composables/useWallet.ts
- frontend/src/formkitTheme.ts
- frontend/src/router/index.ts
- frontend/src/services/transactions/fill-manager.ts
- frontend/src/services/transactions/request-manager.ts
- frontend/src/services/transactions/token.ts
- frontend/src/services/web3-provider/ethereum-provider.ts
- frontend/src/services/web3-provider/metamask-provider.ts
- frontend/src/services/web3-provider/types.ts
- frontend/src/services/web3-provider/walletconnect-provider.ts
- frontend/src/stores/configuration.ts
- frontend/src/stores/ethereum-provider.ts
- frontend/src/stores/settings.ts
- frontend/src/stores/transfer-history/store.ts
- frontend/src/types/token-amount.ts
- frontend/src/utils/create-async-process.ts
- frontend/tests/unit/actions/transfers/transfer.spec.ts
- frontend/tests/utils/mocks/ethereum-provider.ts
- relayer/.eslintrc.js
- relayer/src/service.ts
Since TypeScript 3.8 it is a good practice to use type imports (`import type ...`) where possible. Type imports allow for certain compiler and tooling optimizations.
This rule is auto-fixable. So it doesn't add extra work to the developers. Except the ESLint rule adaption, all changes in this commit are caused by automated fixes.
Note that this got applied to the `relayer` too.
> frontend: enforce type imports

- frontend/package.json
- frontend/src/actions/steps/multi-step-action.ts
- frontend/src/composables/useLoadConfiguration.ts
- frontend/src/composables/useTokenSelection.ts
- frontend/src/services/web3-provider/walletconnect-provider.ts
- frontend/src/stores/ethereum-provider.ts
- frontend/src/types/encoding.ts
- frontend/tests/unit/stores/ethereum-provider.spec.ts
I was a bit annoyed that my IDE showed typescript errors which were not caught by our linting and the CI, so I added tsc to the linting script.
> frontend: Add typescript compiler check to linting

- frontend/src/actions/transfers/transfer.ts
- frontend/src/services/transactions/token.ts
- frontend/tests/unit/actions/transfers/transfer.spec.ts
Somehow I managed to loose the call of the token allowance. As soon as the last allowance is no more enough (always for new users), no transfer is possible anymore.
This simply adds it back, using the still existing utility function, but integrating it as a new first step of a transfer. First time that our new architecture really plays it strength, as we can simply add a news step, at first place, fully backwards compatible and neatly  working.
> frontend: recover token allowance usage

- frontend/src/services/web3-provider/walletconnect-provider.ts
When we worked on the WalletConnect integration, we had some weird issues with importing the dependency. While TypeScript is fine, the application does no more work at all in the browser. Therefore we uses a more specific import of a specific file of the package. That import causes issues with TypeScript due to a missing declaration file.
This issue was solved in the past and working, because we had no TypeScript linting enabled. Recently we enabled the latter and this import got simply fixed, without checking the functionality of the application.
This commit is now recovering the ugly fix of the past and makes the linting pass.
> frontend: fix issues on wallet connect import

- beamer/tests/agent/test_challenge.py
- beamer/tests/contracts/test_request_manager.py
- beamer/tests/contracts/test_request_manager_fees.py
- contracts/contracts/BeamerUtils.sol
- contracts/contracts/RequestManager.sol
There was a bug in the contracts code when a claimer had multiple claims on the same request.
If one of them was successfully withdrawn, all other claims would be resolved in favor of the claimer which could be wrong if the fill id was different.
The rule is: 
All identical claims should be resolved equally. A correct claim is only correct if the claimer is the filler and the fill id matches. If the correct filler creates a claim with a wrong fill id, the claim becomes invalid.
This must be reflected in the withdraw function: In order to achieve that we need to store all relevant information with the request upon deposit withdraw, so that future claims can be resolved correctly. 
That means if the future claim is from the same address who withdrew the deposit AND the fill id is the same …
> Also store fill id in request when withdrawn to correctly resolve other active claims

- frontend/src/components/Transfer.vue
- frontend/src/components/layout/Progress.vue
- frontend/src/components/layout/ProgressStep.vue
- frontend/src/components/layout/WaitingDots.vue
- frontend/tests/unit/components/layout/Progress.spec.ts
- frontend/tests/unit/components/layout/ProgressStep.spec.ts
- frontend/tests/unit/components/layout/WaitingDots.spec.ts
Little weekend PR to implement a little UI feature for our designer. 😉 
A new component called `WaitingDots` got added. This component does an animation of three dots that appear after each other ('' -> '.' -> '..' -> '...' -> '' -> '.' -> ...).
It gets used as an indicator that a `ProgressStep` is currently active (and waiting or doing something).
This includes a missing test case for error messages in progress steps.
> frontend: add waiting dots for active steps

- beamer/agent.py
- beamer/chain.py
- beamer/events.py
- beamer/l1_resolution.py
- beamer/models/claim.py
- beamer/state_machine.py
- beamer/tests/agent/unit/test_handlers.py
- beamer/tests/agent/unit/test_l1.py
- beamer/tests/agent/unit/utils.py
Resolves #669 
- First commit fixes an oversight on the return type of the `_l1_resolution_criteria_fulfilled` function
- Second commit add the `InitiateL1InvalidationEvent`, which is triggered when a claim that has been invalidated can be L1 resolved.
> Trigger L1 invalidation

- frontend/src/components/RequestFormInputs.vue
- frontend/src/components/TransferSummary.vue
- frontend/src/composables/useTokenSelection.ts
When the user has not connected with his wallet yet, the list of selectable tokens is empty even if he has chosen a source chain. The reason was that the tokens get filtered by the connected chain of the wallet, not the selected chain. But the user tends to first put in some values before connecting. Seeing that no token is available is a bad experience.
This is includes a tiny fix to open the block explorer link in a new tab. This somehow got lost during merge conflict resolution.
> frontend: allow token selection without wallet

- beamer/chain.py
- beamer/models/request.py
- beamer/state_machine.py
- beamer/tests/agent/unit/test_handlers.py
This changes the withdraw scheme of the agent to withdraw a claim correctly after a request is l1 resolved
The agent needs to take the l1_filler as well as the fill_if into account
partially related to #645
> Withdraw correctly after l1 resolution

- docs/source/contributing.rst
this option of the deployment script does not exits anymore.
> Docs: Remove --test-messenger option from contributing doc

- beamer/agent.py
- beamer/cli.py
- beamer/util.py
- docker/optimism/optimism.sh
- scripts/_util.py
- scripts/call_contracts.py
- scripts/deployment/main.py
- scripts/e2e-test.py
`call_contracts.py` did not work because of a misconfigured web3 object. The code from e2e-test and the deployment script was reused to setup web3. 
Since all the 3 scripts share the same code to setup web3, load contract information and create an account, I moved the code to `scripts/_util.py` to remove the redundant code.
fixes: #711
> Fix call_contracts.py 

- beamer/events.py
- beamer/models/claim.py
- beamer/models/request.py
- beamer/state_machine.py
- beamer/tests/agent/test_request.py
- beamer/tests/agent/unit/test_handlers.py
- beamer/tests/agent/unit/test_invalidate.py
- beamer/tests/agent/unit/test_l1.py
- beamer/tests/agent/unit/utils.py
- beamer/util.py
Resolves #749
Delay calling the relayer until the finalization period is over.
I decided to store the timestamps in the request and claim objects instead of recalculating it from the transaction every time to save some rpc requests.
> agent: Wait to trigger L1 resolution until finalization

- beamer/state_machine.py
- beamer/tests/agent/unit/test_handlers.py
- beamer/tests/agent/unit/test_l1.py
We may have ignored a request (e.g. due to an unsupported token pair) so
we need to be able to handle cases where we see claims for requests we
do not have. Note that we already do this in _handle_claim_withdrawn.
Fixes: #810
> beamer: don't expect there will be a request if we encounter a claim

- .github/workflows/relayer.yml
- relayer/src/service.ts
The relayer should shut down when the agent crashes for whatever reason.
In that case the relayer process will be reattached to a process higher
in the process tree. This is used to check for the ppid, and shutdown in
case it changes.
Resolves #748 
Also adds basic bundling to the relayer.
Resolves #609
> relayer: Shutdown on ppid change

- .github/workflows/agent-release.yml
- .github/workflows/backend.yml
- beamer/cli.py
- beamer/l1_resolution.py
- beamer/tests/agent/test_cli.py
- pyproject.toml
Ref #739 
This PR adds basic packaging to the agent.
This is done by creating a bundled version of the relayer and including that in the agent package. The code to get the relayer executable is changed, so that it can find the bundles version.
Tested in a local VM:
```
Python 3.9.13 (main, Jun 23 2022, 11:12:54)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.
In [1]: import beamer.l1_resolution
In [2]: beamer.l1_resolution.get_relayer_executable()
2022-06-29 11:53.45 [debug    ] Found packaged relayer         relayer=PosixPath('/abc/venv/lib/python3.9/site-packages/beamer/data/bin/relayer-node16-linux-x64')
Out[2]: PosixPath('/abc/venv/lib/python3.9/site-packages/beamer/data/bin/relayer-node16-linux-x64') …
```
> Agent packaging

- frontend/src/components/inputs/Selector.vue
When submitting a request the UI input was being set to disabled. Unfortunately this caused the UI to "glitch" since the input field and selector dropdown icon backgroudns were white.
By inheriting the background-color from the parent elements the UI stays the same when disabled and one no longer has the feeling that the app is broken.
Without the changes:
With the changes:
the fields are still disabled and if the user goes with the mouse over them he would receive the normal feedback that he cannot do anything in the field.
> Fix UI flashing

- .github/dependabot.yml
This takes to much time, it's better to do it once in  a while by hand.
> ci: Remove dependabot for relayer

- frontend/src/actions/transfers/transfer.ts
- frontend/tests/unit/actions/transfers/transfer.spec.ts
Fixes #854
How to verify the bug got fixed:
- use first an old version of the frontend
- use an account not used yet for Beamer (in fact that has no token allowance for the request manager contract)
- transfer some ETH to this account
- connect the app to the account
- mint some test tokens for this account
- send all tokens to a different account accept 2
- try to make a transfer of 1 TST
- this will set the allowance to 2, as currently it is 0, is needs 1 and sets it to the current token balance of the user
- the allowance step should be green
- the request transaction step should fail (error in UI is `insufficient balance`)
- the error in the console should reveal the contract reverted message because the token allowance is too low
- this could be repeated, the allowance step gets …
> frontend: fix issue of a too low token allowance

- beamer/state_machine.py
fix for removing unusable RequestFilled events. Happens especially during start up and fethcing older events
> agent: drop RequestFilled event if request is in state withdrawn

- frontend/src/components/ImprintModal.vue
- frontend/src/components/RequestDialog.vue
- frontend/src/components/TermsModal.vue
- frontend/src/components/layout/Modal.vue
- frontend/tests/unit/components/layout/Modal.spec.ts
Closes https://github.com/beamer-bridge/beamer/issues/847
Closes https://github.com/beamer-bridge/product/issues/67
This includes a disclaimer which needs to be checked before a transfer can be made. The disclaimer is only shown in production. The `Modal` logic of the `ImprintModal` has been refactored to its own component, so it could be reused for the terms & conditions.
> frontend: Add terms & conditions

- frontend/src/components/TransferHistory.vue
- frontend/tests/unit/components/TransferHistory.spec.ts
Closes #851 
Every transfer group label and every transfer element is now wrapped in a LazyWrapper itself. This fixes the problem that a user needed to scroll to the label to see the whole group. Also, this removes the overhead of every transfer being added to the DOM when the respective group is displayed. As all transfers go eventually into the "older" group, this could have been an performance issue in my opinion.
I would like to have the opinion of @weilbith next week when he is back on this PR. This bug is nothing critical, so this should be fine. I am just wondering how he intended the LazyWrapper to be uses, because my version will create an extra div for every element.
> frontend: Fix transfer history lazy loading

- frontend/src/components/RequestDialog.vue
- frontend/src/components/RequestTargetInputs.vue
Fixes #878
The target address input inside the request form is now reacting
and prefilling the value for the user on wallet address change
(connect/disconnect).
When the user manually entered a different address than his currently
connected wallet address the input will not be touched until
input value was cleared.
> frontend: Add target address prefill function

- docs/source/contributing.rst
Aligned contract compile command to the latest directory structure.
Added missing argument inside contract deploy command which will enable
deploying the mintable token by default.
> docs: update outdated "contributing" docs

- .circleci/config.yml
Since the webhook to circle ci was introduced it blocks PRs. Unfortunately the only way to test circle ci is via github pushing to a branch and then let the CI run. 
To not block other PRs this is the first part of circle CIs config. It runs until lint. 
Until the config is complete we simply let circle and github CI run.
> First part of circle ci config

- beamer/events.py
- beamer/tests/constants.py
- beamer/typing.py
This improves the log output of fill IDs.
~(`fill_id` is typed as `FillId`, which is a newtype of `Hexbytes`, but we get `bytes` instances from `web3`, which means we must convert them)~
We need to convert received `bytes` from `web3` to proper `FillId` which is derived from `HexBytes` to improve repr.
> beamer: events: convert received bytes to HexBytes

- relayer/src/service.ts
The latter will block until one of the promises is fulfilled, or all are
rejected. Since the returnOnPpidChange never rejects, this means the
relayer will be forever stuck in case the main promise rejects (i.e.
throws). Promise.race will instead return as soon as one promise is
rejected, which is what we want here.
Closes: #891.
> relayer: use Promise.race instead of Promise.any

- relayer/src/service.ts
Also print message status and correctly exit the JS process as soon
as one of the promises is resolved.
> relayer: don't do anything if the message has already been relayed

- frontend/.eslintrc.js
- frontend/src/components/RequestDialog.vue
- frontend/src/services/transactions/request-manager.ts
- frontend/src/services/web3-provider/walletconnect-provider.ts
Adding this because I saw this quite often in the recent PRs.
I think it is in general good practice to have the curly braces around any block, because it provides better readability, maintainability and is less prone to errors. See https://stackoverflow.com/questions/4797286/are-braces-necessary-in-one-line-statements-in-javascript for some arguments.
> Frontend: Add eslint rule to require curly braces for blocks

- scripts/deployment/mainnet.json
@istankovic 
Please double check the correctness of the parameters
* Optimism and Boba Messenger addresses
* claimstake = 0.0015
* claimPeriod 1 day in seconds
* challengePeriodExtension 1 day in seconds
* finalityPeriod for both 7 days in seconds
> add mainnet deployment config

- frontend/src/components/RequestSourceInputs.vue
- frontend/src/components/Transfer.vue
- frontend/src/composables/useRequestSourceInputValidations.ts
- frontend/src/composables/useTokenBalance.ts
- frontend/src/composables/useTokenSelection.ts
- frontend/src/services/transactions/token.ts
- frontend/src/types/token-amount.ts
- frontend/tests/unit/types/token-amount.spec.ts
Closes #698, closes #964
default beahavior for the new format() function:
- for values >= 1 shows maximum 5 digits totally or at least 2 decimals
- for values < 1 show 8 decimal places max
- for values < 1 if decimal places would only be 0 show a less than sign (e.g. < 0.001)
Or displays the given decimals from the options.
@GabrielBuragev this does not include the tooltip for displaying the full amount yet. I simply didn't have enough time. Could you add it either here or in a new PR? It should be displayed for the token balance and in the headers in the transfer history
> frontend: Correctly abbreviate long token amounts

- frontend/src/services/transactions/request-manager.ts
Fixes #968 
Seems like the code where the `provider.getTransaction` function was used was not properly checking if the transaction was actually mined in a block or indexed yet therefore making the app crash due to returned `null` values inside the corresponding functions.
From the [official ethers docs](https://docs.ethers.io/v5/api/providers/provider/#Provider-getTransaction) it is clear that the calls to `provider.getTransaction` method are not always returning the values we are expecting currently. When network is congested or for any other reason, mining the blocks might take longer and that needs to be properly accounted for when trying to fetch the transactions from the blockchain.
Knowing this, i switched to using a call to `provider.waitForTransaction` first which expects at least …
> frontend: Fix failing transfers

- beamer/state_machine.py
this is a quick hotfix.
If the agent is in a challenge, the timestamp is finalized but not enough funds are reached it would drop the `initiateL1ResolutionEvent`. This should not be the case. It should only drop once the claim was removed by a withdraw or L1 resolution was triggered
> dont drop InitiateL1ResolutionEvent

- beamer/agent.py
- beamer/tests/agent/test_challenge.py
- beamer/tests/conftest.py
- beamer/tests/contracts/test_fill_manager.py
- beamer/tests/contracts/test_l1_resolution.py
- beamer/tests/contracts/test_request_manager.py
- beamer/tests/contracts/test_request_manager_fees.py
- beamer/tests/util.py
- contracts/contracts/FillManager.sol
- contracts/contracts/LpWhitelist.sol
- contracts/contracts/RequestManager.sol
- scripts/call_contracts.py
- scripts/e2e-test.py
resolves: #893 
For the tests I created a function called `alloc_whitelist_accounts` which takes contracts as an argument and calls `addAllowedLp()` on it. Since it is a util function in must be passed in the arguments.
The positive side on this is that I had to go through all the tests and bring more context to the addresses and give them better names. I also removed some overlappings where the requester was also the claimer (not that it is harmful in particular but it removes the possibgility of failures due to address misusage).
Regarding `call_contracts.py whitelist` I did not come up with a proper solution because the script only consumes one RPC endpoint but it would require two here. Since it is not critical for the audit I suggest to create a follow up issue for that.
> Request manager whitelist

- frontend/package.json
- frontend/src/assets/images/close.svg
- frontend/src/components/WalletMenu.vue
- frontend/src/composables/useWallet.ts
- frontend/src/services/web3-provider/metamask-provider.ts
- frontend/src/utils/userAgent.ts
- frontend/tests/unit/composables/useWallet.spec.ts
- frontend/tests/unit/utils/userAgent.spec.ts
- frontend/yarn.lock
Fixes #937 
Fixes #1015 
This PR contains fixes for several wallet connection flows.
Desktop flows (#937)
---
- MetaMask wallet provider option was enabled even when the MetaMask extension was not installed on the user's browser. 
In this case, when the user makes a selection, the dApp silently fails to connect and shows no relevant information to the user.
With this PR, i included an onboarding process for these cases. 
Now, when the user clicks on the MetaMask button and he has no installed extension, he will be redirected to finish the onboarding process before he can start using the app. 
The dApp autoconfigures itself after onboarding process is finished
Mobile device flows (#1015)
---
After some research on this topic i found out that some of the UX flows (regarding wallet …
> Frontend: improve several wallet connect flows

- frontend/src/components/RequestSourceInputs.vue
- frontend/src/components/RequestTargetInputs.vue
- frontend/src/components/inputs/Selector.vue
- frontend/src/stores/portals.ts
- frontend/src/views/Home.vue
- frontend/tests/unit/components/inputs/Selector.spec.ts
- frontend/tests/unit/stores/portals.spec.ts
Fixes #898 
This brings a new approach to how the app handles multiple Teleports on same target. Until now, the first element inside the Teleport target was displayed.
This makes it harder to control and override the content of the Teleport target since Vue Teleport component works only in [append mode](https://vuejs.org/guide/built-ins/teleport.html#multiple-teleports-on-the-same-target). 
There was a need of hiding the current displayed content inside the form action button when the selector view was open. 
In order to avoid introducing another store for managing such minor misc things, or another complex solution which might require communication between 3+ levels of components i settled down on using an approach where the most recently added element to the Teleport target is …
> frontend: Add back button on selector view & hide action button when selector view is opened

- frontend/src/App.vue
- frontend/src/components/RequestDialog.vue
fixes #935 
Logo was removed on mobile devices since it was just being overlayed by the dialog and no other design solution was provided.
Aligned with Olympe and for now we will stick to this approach.
> frontend: fix mobile layout to fit small screens

- beamer/models/claim.py
- beamer/models/request.py
- beamer/state_machine.py
We need to store invalid fillIds in the request object. This is due to the fact, that due to not processing preceding events, the claim creation can happen after processing invalidation events.
> Store invalid fill ids in request

- frontend/src/components/layout/Tooltip.vue
- frontend/tests/unit/components/layout/Tooltip.spec.ts
Fixes #987
This does two things:
1. position the tooltip conditionally on the right of the main container or below the content element depending on if it fits in the viewport. (The tooltip did not have enough space on the right on mobile)
2. add the touch events to also make it work in an mobile environment.
> Frontend: fix tooltip for mobile

- frontend/src/components/WalletConnectionDetails.vue
- frontend/src/components/WalletMenu.vue
- frontend/src/components/wallet/ConnectionError.vue
- frontend/src/composables/useWallet.ts
- frontend/tests/unit/components/WalletConnectionDetails.spec.ts
- frontend/tests/unit/components/WalletMenu.spec.ts
- frontend/tests/unit/components/layout/Tabs.spec.ts
- frontend/tests/unit/components/wallet/ConnectionError.spec.ts
- frontend/tests/unit/components/wallet/Disconnect.spec.ts
closes #587 
Adds the missing tests for the `WalletMenu`. Also refactors the `ConnectionError` to not use a slot in order to be consistent with the `Disconnect`. Hope this is fine. I must have overlooked it in the PR review.
Additionally, I fixed the warnings that were shown during test runs.
> frontend: Add missing unit tests for simple components

- frontend/index.html
Solves a small part of the issue: #1131 
Seems like [Piwik is not tracking](https://stackoverflow.com/questions/13688749/piwik-localhost-tracking) `localhost` activity by default therefore there was no need to avoid script loading inside dev environment.
> frontend: include matomo tracking script

- frontend/index.html
closes #1155
Added:
tracking visitors across all subdomains
prepend the site domain to the page title when tracking outlines report hide clicks known alias URLS of beamer based on https://developer.matomo.org/guides/tracking-javascript-guide#measuring-domains-andor-sub-domains
> Added subdomain tracking

- frontend/src/components/RequestSourceInputs.vue
- frontend/src/composables/useMaxTransferableTokenAmount.ts
- frontend/src/services/transactions/request-manager.ts
- frontend/src/services/transactions/utils.ts
- frontend/src/types/uint-256.ts
- frontend/tests/unit/composables/useMaxTransferableTokenAmount.spec.ts
- frontend/tests/unit/services/transactions/request-manager.spec.ts
- frontend/tests/unit/services/transactions/utils.spec.ts
- frontend/tests/unit/types/uint-256.spec.ts
Fixes #1127 
I adjusted the `UInt256` abstraction to not support creation of negative integers since that was contradictory to what this class is supposed/expected to do (unsigned should stand for positive only). It was necessary to adjust it as so since i introduced arithmetic operations over it.
Also includes a solution to [Manuel's suggestion](https://github.com/beamer-bridge/beamer/issues/1127#issuecomment-1278048533)
> frontend: fix "use max token balance" feature

- frontend/src/validation/validators.ts
- frontend/tests/unit/validation/validators.spec.ts
closes #1152
Note on the discussion we had for limiting the user input to only valid numeric values: 
It's not going to be included in this PR as i didn't want to block the merging of this bugfix. In any case, that implementation would still not fix the bug described in #1152 so these 2 things are unrelated. I created a separate issue for this [here](https://github.com/beamer-bridge/beamer/issues/1165)
> frontend: avoid unallowed token amount input state

- .circleci/config.yml
- .github/workflows/backend.yml
The newer 1.0.0-rc.1 causes unnecessary formatting changes and this is intended to fix our CI until we decide how to handle those changes.
> .github: go back to prettier-solidity-plugin 1.0.0-beta.19

- frontend/config/chains/10.json
- frontend/config/chains/1337.json
- frontend/config/chains/28.json
- frontend/config/chains/288.json
- frontend/config/chains/588.json
- frontend/config/chains/chain.ts
- frontend/config/schema.ts
- frontend/src/components/Transfer.vue
- frontend/src/composables/useChainSelection.ts
- frontend/src/services/web3-provider/ethereum-provider.ts
- frontend/src/services/web3-provider/types.ts
- frontend/src/types/data.ts
- frontend/tests/unit/components/Transfer.spec.ts
- frontend/tests/utils/data_generators.ts
Closes #1124 
When adding a chain to the connected wallet, the explorer URL is now added. This also changes our config files by renaming `explorerTransactionUrl` to `explorerUrl` and removing the `/tx` path from the urls. This can be safely done as explorer routes are standardized in EIP-3091. Furthermore, the `addChain` was changed in that way that it now consumes the usual `Chain` type instead of the `ChainData` type. The `ChainData` type was added when we did not have the split types of the configuration and is redundant now. Same goes for `Token` and `TokenData`.
> frontend: Add explorer URL to wallet

- beamer/tests/contracts/test_request_manager.py
- contracts/contracts/RequestManager.sol
Closes #1051
This enables easily checking if the deposit for a request was withdrawn or not.
For the tests, I added calls to the new function in the withdrawal test functions, in order to not duplicate the whole test setup for this simple function. Only the withdrawal state for a new request got its own test.
> contracts: Add isWithdrawn() function to request manager

- beamer/agent.py
- beamer/chain.py
- beamer/state_machine.py
- beamer/tests/agent/unit/test_handlers.py
- beamer/tests/agent/unit/utils.py
- beamer/tests/conftest.py
- beamer/tests/constants.py
- beamer/tests/contracts/test_request_manager.py
- contracts/contracts/RequestManager.sol
- docs/source/protocol.rst
- scripts/deployment/arbitrum-local-template.json
- scripts/deployment/ganache-local.json
- scripts/deployment/main.py
- scripts/deployment/mainnet.json
- scripts/deployment/optimism-local-template.json
- scripts/deployment/rinkeby_testnets.json
Allows claiming after request expiry. Time is bounded by claimRequestExtension.
I went for the strict approach to introduce a new variable `claimRequestExtension`. Same as we did with claimPeriod and challengePeriodExtension which follow the same principle: Give an actor enough time to react.
In the future we can think about merging these values together, but for now I wanted to keep the pattern and create an explicit value.
> contracts: allow claim until validUntil + claimRequestExtension

- brownie-config.yaml
- contracts/contracts/FillManager.sol
- contracts/contracts/LpWhitelist.sol
- contracts/contracts/MintableToken.sol
- contracts/contracts/RequestManager.sol
- contracts/contracts/Resolver.sol
- contracts/contracts/RestrictedCalls.sol
- contracts/contracts/StandardToken.sol
- contracts/contracts/chains/arbitrum/ArbitrumMessengers.sol
- contracts/contracts/chains/optimism/OptimismMessengers.sol
This PR updates OpenZeppelin to 4.8.0, which is the version that has the latest Nitro contracts. We also update the Arbitrum nitro submodule to latest master. Finally, we remove the now unnecessary `calculateRetryableSubmissionFee` implementation.
> Arbitrum support, continued

- beamer/tests/contracts/test_fill_manager.py
- beamer/tests/contracts/test_request_manager.py
- contracts/contracts/FillManager.sol
- contracts/contracts/LpWhitelist.sol
- contracts/contracts/RequestManager.sol
Closes #1201 
This overloads the `claimRequest` function with an additional parameter for setting the claimer. This means the claim can be initiated by another address than the claimer address. The initiator pays the stake. The claimer gets the stake distribution back. Adds a new modifier to the LpWhitelist in order to check if the given claimer is whitelisted.
> Contracts: claim on behalf of others

- poetry.lock
- pyproject.toml
This allows us to move forward with brownie version and other dependencies.
> pyproject.toml: unpin lru-dict

- frontend/src/services/web3-provider/ethereum-provider.ts
- frontend/tests/unit/services/web3-provider/ethereum-provider.spec.ts
Fixes #1118 
MetaMask sometimes throws a disconnect event when switching the chain. In this case we need to ignore the event, because the account is actually still connected. This adds a flag that is true for 1 second after a chain switch happened. A short time period is necessary because the event is not directly thrown when the `wallet_switchEthereumChain` rpc method returns. If this is fixed on the side of MetaMask, we can remove the flag again.
> frontend: Hotfix for MetaMask throwing disconnect events when switching chain

- frontend/src/composables/useTransferRequest.ts
- frontend/tests/unit/composables/useTransferRequest.spec.ts
closes #1340 
When creating a transfer, the request manager was queried for the fees of the target token address (which only exists on the target chain). This obviously returns an erroneous value as the request manager only knows about the source token address. This led to the bug that the fees were not taken into account for the getting the token allowance. This simply changes the `getRequestFee` call to use the correct variable.
> frontend: Fix fee query on transfer creation

- beamer/agent.py
- beamer/state_machine.py
- beamer/tests/agent/test_request.py
The request object needs to be transitioned to state claimed once a ClaimMade event emitted by the agent happens. 
Note that the state claimed is only relevant for request objects which are filled by the agent.
If a request is filled by somebody else then we may not proceed to the claimed state. 
fixes: #1319
> Request state change upon own ClaimMade event

- docker/Dockerfile.agent
The -alpine image does not have the C++ runtime lib, which is required by our relayer binaries.
> docker: Dockerfile.agent: use python:3.10-slim instead of -alpine

- relayer/src/services/arbitrum.ts
Reducing the `MAX_MESSAGE_LENGTH_BYTES` so we avoid depositing unnecessary huge amount of funds on ArbitrumL1Messenger contract.
Read commit message for more info.
> relayer: reduce max message length

- .circleci/config.yml
- .circleci/workflows.yml
- relayer/.gitignore
- relayer/jest.config.ts
- relayer/package.json
- relayer/src/map.ts
- relayer/src/relayer-program.ts
- relayer/src/services/types.ts
- relayer/tests/unit/common/network.spec.ts
- relayer/tests/unit/common/process.spec.ts
- relayer/tests/unit/map.spec.ts
- relayer/tests/unit/relayer-program.spec.ts
- relayer/tests/utils/data_generators.ts
- relayer/tsconfig.json
Closes #1296 
This adds basic unit test coverage for the relayer. As discussed with @GabrielBuragev the actual relaying services are not tested as they rely on libraries and would involve heavy mocking. For the same reason there are no tests for the `service.ts` file.
> relayer: add unit tests

- frontend/src/services/transactions/request-manager.ts
- frontend/tests/unit/services/transactions/request-manager.spec.ts
- frontend/tests/utils/mocks/ethers.ts
We were fetching the transaction receipt and were always assuming that if we have a tx receipt we have a succesfull tx. In some situations though, we had reverted transaction. We were trying to parse the logs on those, which triggered a js error: `Cannot read properties of undefined (reading 'topics')`
We now check the receipt status and try to parse the logs only if it is succesful.
> frontend: deal better with reverted txs

- frontend/src/App.vue
- frontend/src/components/RequestDialog.vue
- frontend/src/components/TransferWithdrawer.vue
- frontend/src/stores/transfer-history/store.ts
- frontend/src/views/Home.vue
- frontend/tests/unit/stores/transfer-history/store.spec.ts
If the user has another transfer pending, we prevent the user from submitting a second transfer.
We don’t treat a transfer to be pending if the user has signed all transactions and they’ve been mined. If that is the case and an agent still hasn’t fullfiled the request - this is not a pending transaction.
The reason we do that is that before submiting a transaction we check the allowance and create an allowance tx. But if the actual transaction that submit the money to the contract is not mined yet, then the second tx that the user starts has an incorrect allowance and the tx that sends the money to the contract fails with "incorrect allowance".
We are currently outputting this message:
I've moved the footer to an absolute position and suck it on the bottom of the page. I applied bottom …
> frontend: prevent user from submitting a second tx

- frontend/package.json
- relayer/package.json
The frontend had no license specified in its `package.json`.
> frontend: add GPL license

- frontend/index.html
- frontend/src/App.vue
- frontend/src/components/MatomoConsentPopup.vue
- frontend/src/stores/settings.ts
- frontend/tests/unit/components/MatomoConsentPopup.spec.ts
- frontend/tests/unit/stores/settings.spec.ts
Closes #1375 
Stops Matomo tracking until the user accepts it in the pop up. Consent information is stored in Matomo.
@olympe-silve please check in the screenshot if the styling of the pop up is ok like this:
> frontend: Add MatomoConsentPopup

- beamer/agent.py
- beamer/chain.py
implements: #1425 
I decided to not go for a method to add a callback, as all EventProcessors will be static for now. They will all be created before the EventMonitor is initialized.
> agent: allow lists of event callbacks to be added to the EventMonitor

- frontend/src/services/web3-provider/ethereum-provider.ts
- frontend/src/services/web3-provider/metamask-provider.ts
- frontend/tests/unit/services/web3-provider/ethereum-provider.spec.ts
- frontend/tests/unit/services/web3-provider/metamask-provider.spec.ts
Closes #1118 
Slow RPCs can still lead to the problem that after a chain switch a wallet disconnection occurs. Looks like the timeout of 1 second is not enough. To fix it deterministically, I removed the listener on the disconnect event completely. The listener was used to catch the case when a user clicks disconnect inside MetaMask. In this case also an accountsChanged event is fired. We can simply rely on this event to call our disconnect function. I also removed the no disconnection after chain switch test as it is not applicable anymore. There is no test, because I think the new behavior is not coverable in a unit test.
> frontend: Fix wallet disconnection after chain switch

- beamer/chain.py
- beamer/events.py
- beamer/tests/util.py
I saw two solutions: 
Either throwing the error up until the point where `on_sync_done()`, namely the EventMonitor. I didn't like that option because I think handling request exceptions inside of the EventFetcher is the right place.
The other option, was to check whether the fetch call synced up until a certain point. I went with that option. Fetching the BlockNumber before calling fetch() for the sync. Exposing the latest synced block by a property in the EventFetcher. And checking whether the fetcher synced at least until this block.
I realized that not only the ConnectionError described in #1435  is a problem, also a RequestException during fetching the blockNumber in https://github.com/beamer-bridge/beamer/blob/9935c4ab77044d17645329e68c0e259639cebab0/beamer/events.py#L288 results in …
> Handle ConnectionError on sync

- .circleci/workflows.yml
It won't be initialized by default so we have to do it manually before initializing its submodules.
> .circleci: properly init the nitro submodule

- frontend/src/components/Version.vue
- frontend/tests/unit/components/Version.spec.ts
- frontend/vite.config.ts
closes #1474 
Please note, this solution won't work with forked repositories so it is tailored only for use with our official repo (repository URL value is a static `https://github.com/beamer-bridge/beamer` instead of a dynamic value based on `git ls-remote --get-url`).
When using `git ls-remote --get-url` for determining the repository URL we had several problems for which i couldn't find a simple yet inclusive solution:
- determining the HTTPS URLs when the local repo config is using SSH URLs
- not exposing the sensitive information stored inside `git config` (like github access tokens etc.). Check #1474 for more info.
If someone has any suggestion on how to tackle all of this at once with a simple command please let me know.
> frontend: Fix app release version repository URL

- frontend/src/env.d.ts
- frontend/src/stores/transfer-history/store.ts
- frontend/tests/unit/stores/transfer-history/store.spec.ts
- frontend/vite.config.ts
After merging & deploying the commit hash url inside the footer we introduced a bug where the transfer history is reset to an empty array. This fixes it and will bring back the old transfer history for all the users.
However, users that used our app since Feb 14 will not see their new transfers but will see their old transfers that they made before Feb 14
> frontend: fix transfer history load failure

- frontend/src/App.vue
- frontend/src/actions/transfers/transfer.ts
- frontend/src/components/Footer.vue
- frontend/src/components/RequestDialog.vue
- frontend/src/composables/useTokenAllowance.ts
- frontend/src/composables/useTransferRequest.ts
- frontend/src/services/transactions/token.ts
- frontend/src/types/uint-256.ts
- frontend/src/views/Home.vue
- frontend/tailwind.config.js
- frontend/tests/unit/actions/transfers/transfer.spec.ts
- frontend/tests/unit/composables/useTokenAllowance.spec.ts
- frontend/tests/unit/composables/useTransferRequest.spec.ts
- frontend/tests/unit/services/transactions/token.spec.ts
- frontend/tests/unit/types/uint-256.spec.ts
closes #1071 
Adds a checkbox below the transfer dialog which allows users to decide to approve an infinite amount of their tokens. Makes the token allowance transaction of future transfers obsolete for them.
I did some refactoring of the css of the app's main div, because we were not using tailwind there.
> frontend: Add infinite token approval checkbox

- beamer/tests/agent/test_challenge.py
- beamer/tests/agent/test_rate_limiter.py
- beamer/tests/agent/test_read_timeout.py
- beamer/tests/agent/test_request.py
- beamer/tests/util.py
This is to allow arbitrary behaviour when making POST requests.
> beamer: tests: make HTTPProxy more generic

- beamer/health/health-check-mainnet.conf
In the process of reviewing: https://github.com/beamer-bridge/run-your-own-agent/pull/17 we found out that we had the wrong example config structure. This PR fixes it.
> agent: health: fix wrong example config

- frontend/src/components/RequestDialog.vue
- frontend/src/services/web3-provider/ethereum-provider.ts
- frontend/src/services/web3-provider/metamask-provider.ts
- frontend/tests/unit/services/web3-provider/ethereum-provider.spec.ts
- frontend/tests/unit/services/web3-provider/metamask-provider.spec.ts
- frontend/tests/utils/mocks/ethereum-provider.ts
Closes #1513 
Ensures that no transfers are shown mistakenly as failing with Bitkeep. During testing I also found that the chain switching does not work properly with Bitkeep. This is also fixed. See commit messages for details.
> Frontend: fix bugs in Bitkeep mobile wallet

- frontend/config/chains/1.json
- frontend/config/chains/5.json
- frontend/config/tokens/DAI.json
- frontend/config/tokens/USDC.json
- frontend/public/images/ethereum.svg
closes #1396 
Note: Ethereum will not be included as an option on the frontend until we deploy the contracts and update the files inside `deployments/mainnet` & `deployments/testnet` on main branch with that latest deployment. The frontend automated config script works in a way that it doesn't configure/display chains that cannot be found in those `deployment.json` files.
So, after merging this and until the moment we deploy and merge the deployment artifacts to main branch we are safe to re-deploy the frontend.
> Frontend: Add Ethereum config files

- .circleci/workflows.yml
This PR updates Python to 3.10.10, latest in the 3.10.x series as of now. Also poetry is updated to the latest version, 1.4.1.
(We have to use the `--no-ansi` option to actually make it work under CircleCI, see commit message for more details.)
Finally, we also update the VM image we are using so we get the newer versions of Docker, npm etc.
> Update to python 3.10.10

- frontend/src/services/web3-provider/ethereum-provider.ts
- frontend/tests/unit/services/web3-provider/ethereum-provider.spec.ts
Closes #1575 
The location.reload function does not work in some Android webviews. I don't know the reason for that, but I could verify that the replace function works. This ensures our ethereum provider works properly after switching the chain.
We still have the issue that MetaMask mobile is not switching the chain after a user selects a different one in our UI. I will create a separate issue. It's hard to debug because they want devs to build there app themselves, otherwise the debugging mode for the dev console is not available.
> frontend: Use location.replace for reload after chain switch

- frontend/src/services/web3-provider/metamask-provider.ts
- frontend/tests/unit/actions/steps/multi-step-action.spec.ts
- frontend/tests/unit/actions/transfers/transfer.spec.ts
- frontend/tests/unit/services/transactions/request-manager.spec.ts
- frontend/tests/unit/services/web3-provider/metamask-provider.spec.ts
Closes #1617 
MetaMask Mobile wraps the error code differently. Actually it is a bug: https://github.com/MetaMask/metamask-mobile/issues/3312 . We can still handle the code because it is also wrapped inside the error object. This is necessary because without it, the `wallet_addEthereumChain` rpc was not triggered in case the wallet does not know the chain yet.
Additionally, I fixed some of our tests which didn't await .rejects assertions.
> frontend: Handle MetaMask Mobile error in switchChain of MetaMaskProvider

- beamer/agent/events.py
- beamer/agent/state_machine.py
- beamer/health/check.py
- beamer/tests/agent/test_request.py
- beamer/tests/agent/unit/test_handlers.py
- beamer/tests/agent/unit/test_invalidate.py
- beamer/tests/agent/unit/test_l1.py
- beamer/tests/agent/unit/utils.py
- beamer/tests/health/conftest.py
As ChainUpdated event in RequestManager has chain_id, this conflicts with Event.chain_id in our agent event representation and chain_id field in ChainUpdatedEvent is rewritten. In order to prevent this, we need to rename chain_id in our agent representation to something else like event_chain_id so it wont get overwritten.
> Rename chain_id to event_chain_id

- beamer/agent/util.py
- beamer/tests/agent/test_pending_tx_handling.py
We now wait indefinitely for tx receipt.
One thing to note here is that the `timeout` parameter to `transact` is not so useful as it was before.
Before: setting `timeout=N` would set an upper bound on the runtime of `transact`
After: setting `timeout=N` would not have an effect on the upper bound on the runtime of `transact`
(I'm ignoring the `attempts` parameter and internal `transact` call of course)
Since we've started to use `transact` all over the place, I think we should keep this change of behaviour in mind.
Closes: #1667
> Handle pending tx

- frontend/src/composables/useRequestSourceInputValidations.ts
- frontend/tests/unit/composables/useRequestSourceInputValidations.spec.ts
Closes #1641 
Wrong transfer limits could be shown to the user if they switched the token. Somehow it was necessary to wrap the `makeMaxTokenAmountValidator` call in an arrow function. Same issue exists a few lines below in the creation of the balance validation.
> frontend: Fix reactivity of transfer limit validation

- .circleci/config.yml
- Makefile
- docs/source/index.rst
- scripts/generate-contract-addresses-doc-page.py
This PR adds a script (with a terribly long name, suggestions welcome!) to generate a doc page with contract addresses, given a deployment file. The script expects JSON on stdin and outputs rst  to be included in the docs.
The Makefile targets are updated and also CI config is changed so that whenever the mainnet deployment file is changed, the page will be regenerated and uploaded.
Example for the current deployment:
> Docs contract addresses

- .circleci/workflows.yml
Is there a reason why this was missing?
> ci: e2e optimism requires create-relayers job

- Makefile
First, make sure that the dist directory exists (it could be missing as a result of running the clean target, for example).
Second, fail if poetry detects an inconsistency between pyproject.toml and poetry.lock. This is to avoid situations where shiv bundles packages from pyproject.toml, and we test everything with packages from poetry.lock.
> Makefile: improve the dist-exe target

- .circleci/workflows.yml
- docker/scripts/test-container-image.sh
- docs/source/releasing.rst
- scripts/dump-private-key.py
This PR
- adds a script that tests the beamer container image
- updates CI workflows so that the `build-and-publish-container-image` is run as part of `backend` and `relayer` workflows; pushes to the container registry will only be done if we're on `main` branch
The test consists of starting a local ganache instance, deploying Beamer onto it, running an agent using the specified container image and checking whether the agents was able to sync successfully.
> docker: scripts: add a container image test

- beamer/agent/agent.py
- beamer/agent/chain.py
- beamer/agent/events.py
- beamer/health/check.py
- beamer/tests/agent/test_challenge.py
- beamer/tests/util.py
Closes: #1729 
This PR looks for notifications from EventFetcher and EventMonitor and pushes the state to EventProcessor and if rpc is not working, EventProcessor halting processing claims and requests.
> feat: check rpc status notifications and halt event processors

- docs/source/releasing.rst
Make it also more robust and always trigger the CI run manually after pushing the release tag.
> docs: improve wording in the description of the release steps

- frontend/config/chains/1.json
When connected via walletconnect to our production app most of the rpc requests fail with the following error:
```
Failed to deserialize the JSON body into the target type: skipCache: unknown field `skipCache`, expected one of `jsonrpc`, `id`, `method`, `params` at line 1 column 74
```
The issue comes from the public rpc url we are using in our app: `https://eth.llamarpc.com`
This PR Fixes this by replacing the public rpc url our app uses to do simple rpc calls.
> frontend: replace broken ethereum rpc

- .circleci/workflows.yml
- deployments/scripts/create-package.sh
In addition to tagging the dev release as dev, this PR also fixes a bug that would prevent the building of the npm package
> deployments: tag dev npm package with the dev tag

- Makefile
- docs/source/contributing.rst
Add `install` command to Makefile, which consolidates following:
```
yarn install
poetry install
ape compile
```
and conditionally fixes `atomics` problem on arm64 chips.
> Add arm64 atomics fix script

- beamer/deploy/config.py
- beamer/deploy/util.py
This PR is solving following issues:
1. To support Polygon ZkEVM, messengers can accept integer in constructor. Config changed.
2. Old resolver args function cant handle int as argument because it looks for "$" in arg.
> fix: solve deployment related issues

- scripts/call_contracts.py
- scripts/verify-contracts.py
This PR fixes 2 things:
1. Verify contracts script was missing a contract if contract name is not unique like we have for base and optimism (OptimismL1Messenger)
2. Fixing the call for totalFee in call-contracts.
> fix: contract verification

- docker/arbitrum/arbitrum.sh
- docker/ethereum/ethereum.sh
- docker/optimism/optimism.sh
- docker/scripts/common.sh
Closes #1805
There might be the case in the e2e tests that a message was not finalized yet and the relayer is already started. To align with the agent, the e2e tests should restart the relayer. For the implementation, I separated the execution of the relayer in a new python script.
> Fix flaky e2e test due to unfinalized message

- beamer/cli.py
- beamer/config/commands.py
- beamer/config/state.py
- beamer/deploy/commands.py
- beamer/events.py
- beamer/tests/agent/test_request.py
- beamer/tests/agent/unit/test_handlers.py
- beamer/tests/agent/unit/test_invalidate.py
- beamer/tests/agent/unit/utils.py
- beamer/tests/config/test_read.py
- beamer/tests/config/util.py
- beamer/tests/health/conftest.py
- docs/source/commands.rst
This PR does a few preparatory steps first (add a way to skip commit checks when deploying, add address field to events) and then adds the implementation of the new `config read` command. Finally, several tests are made that exercise 
- reading state from contract deployment
- reading state starting from an already existing state
- reading state that has a mismatched checksum
There is one `TODO` item in the test code, namely, in the test for checksum mismatch. We can't test this properly now due to a presumed `apischema` bug. That will be investigated independently of this PR and once a fix is found, we will update the code marked by `TODO`.
Closes: #1831
> Add a new command, 'config read'

- deployments-npm-package/scripts/create-package.sh
Since we fixed the incorrect commit hash issue with the goerli artifacts (by redeploying on goerli) we can now re-enable the abi generation in the npm package.
> npm: use generate script for goerli artifacts

- .circleci/workflows.yml
Fixes the incorrect dependency definitions of the `build-and-publish-container-image` job inside the `relayer` workflow. 
The current definition of the `relayer` workflow results in the following flow: https://app.circleci.com/pipelines/github/beamer-bridge/beamer/3132/workflows/2b23d0ef-783f-422e-9447-b0439830029c
It should instead be looking like: https://app.circleci.com/pipelines/github/beamer-bridge/beamer/3127/workflows/c7c203e2-d67d-454d-8db8-b116bd0b4558
> .circleci: update container image workflow deps

- relayer/src/services/relayer/ethereum.ts
Previously, the ethereum relayer service was only able to recover the L1 transaction hash for relays that happened on Mainnet as it was only using the `RESOLVER_DEPLOY_BLOCK_NUMBER` for L1 Mainnet.
This PR adds the capability of recovering the L1 transaction hashes both on Testnet and Local net.
Note: This is properly addressed in https://github.com/beamer-bridge/beamer/pull/1804 by pulling the deployment infos from the npm package instead of having them hardcoded, so consider this a quick & temporary fix.
> relayer: use resolver block number per chain

- frontend/index.html
Closes #1935 
When the Beamer app is loaded in an iframe (this is for example the case with Safe), Matomo's `setCookieSameSite` must be set to `None` in order to use the consent cookie.
Inform the Safe team in the issue once this is merged.
> frontend: Allow Matomo cookie inside iframe

- .circleci/workflows.yml
- docker/polygon_zkevm/polygon_zkevm.sh
The previous deployer account 0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266 is actually being used by polygonZkEVM as a sequencer account. Using the same account sometimes causes a “nonce too low” error since the clients can’t agree on the correct current nonce.
Instead of this account, we use one of the accounts available on the node with funds:
https://github.com/0xPolygonHermez/zkevm-node/blob/develop/docs/running_local.md
After that we use the deposit script https://github.com/0xPolygonHermez/zkevm-bridge-service/blob/develop/test/scripts/deposit/main.go to fund the account on L2.
> Polygon zkevm fix flaky test

- beamer/config/commands.py
- beamer/tests/config/test_read.py
- beamer/tests/config/test_write.py
Small improvements to config commands:
- say whether any config updates have been found and, if yes, how many
- create state path parent directories as needed in case they don't exist
- additional check in the `read` command to make sure deployment and config chain IDs are same
- more tests for the `read` command
> Commands improvements

- beamer/agent/chain.py
- beamer/agent/models/claim.py
We need to wait for finality period that starts after prove operation for OP.
> fix: change fill/invalidation timestamp after prove for op

- docker/arbitrum/arbitrum.sh
- docker/ethereum/ethereum.sh
- relayer/package.json
- relayer/src/cli/programs/prove-op-message.ts
- relayer/src/cli/programs/relay.ts
- relayer/src/services/relayer/arbitrum.ts
- relayer/src/services/relayer/boba.ts
- relayer/src/services/relayer/ethereum.ts
- relayer/src/services/relayer/optimism.ts
- relayer/src/services/relayer/polygon-zkevm.ts
- relayer/src/services/types.ts
- relayer/tests/unit/cli/programs/relay.spec.ts
- relayer/tests/unit/ethers/json-rpc-provider.spec.ts
- relayer/tests/unit/map.spec.ts
- relayer/tsconfig.json
closes #1911 
closes #1693
I reused the logic for recovering the transaction hash of the Ethereum service. Could actually be used by any chain.
> Relayer: Recover l1 transaction hash in Arbitrum relayer service

- beamer/config/commands.py
The contract can emit multiple LpAdded events with the same address.
Closes: #2056
> beamer: config: don't add duplicate entries to whitelists

- beamer/deploy/config.py
- deployments/config/goerli/1442-polygon-zkevm.json
- deployments/config/goerli/420-optimism.json
- deployments/config/goerli/421613-arbitrum.json
- deployments/config/goerli/5-ethereum.json
- deployments/config/goerli/84531-base.json
- deployments/config/local/1001-polygon-zkevm.json
- deployments/config/local/1337-ethereum.json
- deployments/config/local/412346-arbitrum.json
- deployments/config/local/901-optimism.json
- deployments/config/mainnet/1-ethereum.json
- deployments/config/mainnet/10-optimism.json
- deployments/config/mainnet/1101-polygon-zkevm.json
- deployments/config/mainnet/42161-arbitrum.json
It's not necessary and the deployment commands do not use the field.
> Remove tokens from deployment config

- frontend/src/App.vue
- frontend/src/components/ShareTweet.vue
- frontend/src/components/layout/Banner.vue
- frontend/tests/unit/components/ShareTweet.spec.ts
Based on the internal discussion, we are using a similar base text for both the zebra and the polygon zkevm campaign but render the zebra one whenever a transfer has been subsidized.
> Frontend: update campaign texts

- deployments-npm-package/package.json
Currently v2.0.2 doesn't contain the base artifacts.
We have a dev. version that has those, but I would like to pin the frontend for base against a non-dev version.
> deployments: publish version 2.0.3

- .circleci/config.yml
- deployments-npm-package/package.json
- deployments-npm-package/scripts/create-package.sh
Breaking change!
Currently we generate the abis without the bytecode. We do this because the frontend doesn’t use the bytecode. However the agent and backend code needs the bytecode.
The abis now generated in /abis/ will have the bytecode by default. If someone needs abis without the bytecode they are in the abis-without-bytecode folder.
> deployments: create package with abi bytecode

- beamer/config/commands.py
- beamer/tests/config/test_write.py
I noticed some bugs in the config read command
We don't have the concept of removing a token and a chain in the read command and state representation (For the whitelist it works). Instead when we remove a token (or a chain), we define a removal by setting all values back to the default values (i.e. updateToken(address=TOKEN_ADDRESS, transferLimit=0, ethInToken=0). 
The read command will read the respective TokenUpdated events and simply update the state representation. This results in something like
```
"tokens": {
"USDC": {
"transfer_limit": 0,
"eth_in_token": 0
}
},
```
What we actually want is realizing that this is per definition a token removal and thus remove it from the dictionary. Otherwise we would be "spammed" by old removed tokens in the state representation.
We recently had …
> Update Config Read

- beamer/config/commands.py
- beamer/tests/config/test_read.py
The same thing was missing for chains. 
Removing chains should result in removing it from the dicitonary.
> beamer: config: remove chain from dictionary if reset to default values

- beamer/check/commands.py
- beamer/cli.py
- beamer/tests/check/test_invalidations.py
- docs/source/commands.rst
This PR is part of #1646, adding the `beamer check initiate-l1-invalidations` command.
> Beamer check: add initiate-l1-invalidations command

- scripts/generate-abi.py
This will remove ast field in ape compile output files and reduce the size.
> feat: disable ast in abi files

- deployments-npm-package/package.json
Uses the improved generate-abi script that dumps ~4x smaller ABI files
> deployments: bump npm package version to `v3.0.1`

- docs/source/development.rst
> docs: development: document how to run L1 invalidation and challenge checks
